// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.456Z
// Collection: rpsMatches/$matchId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Onchain 1v1 Rock-Paper-Scissors match. Creator picks a buy-in tier (SOL) or any positive amount (MNY) and pays into a per-match escrow PDA. Opponent joins by matching the buy-in. Best-of-3: first player to 2 round wins takes 99% of the pot, 1% platform fee goes to the FEE_POOL_ID PDA (SOL) or SPIN_POOL_ID PDA (MNY) — consistent with the coinflip game. Round commit/reveal coordination is offchain in the rounds subcollection. Status transitions: waiting -> active -> complete | abandoned. If a match goes inactive while 'active' for more than RPS_ABANDON_TIMEOUT_SECONDS, any authenticated user can transition it to 'abandoned' which refunds both players their original buyInLamports from the escrow. Frontend-signed (no backend vault).
 */

export interface RpsMatchesRequest {
  creator: AddressType;
  opponent: AddressType;
  buyInLamports: number | TimeOperation | IncrementOperation | TokenAmount;
  status: string;
  creatorWins: number | TimeOperation | IncrementOperation | TokenAmount;
  opponentWins: number | TimeOperation | IncrementOperation | TokenAmount;
  currentRound: number | TimeOperation | IncrementOperation | TokenAmount;
  winner: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  buyInCurrency: string;
  lastActivityAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface RpsMatchesResponse {
  creator: string;
  opponent: string;
  buyInLamports: number;
  status: string;
  creatorWins: number;
  opponentWins: number;
  currentRound: number;
  winner: string;
  createdAt: number;
  buyInCurrency: string;
  lastActivityAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a RpsMatches operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildRpsMatches(matchId: string, data: RpsMatchesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `rpsMatches/${matchId}`, document: doc };
}

/**
 * Any authenticated user creates a 1v1 RPS match as the creator. Must specify buyInCurrency ('SOL' or 'MNY'). For SOL, must pick one of three valid buy-in tiers (COINFLIP_TIER1/2/3_LAMPORTS = 0.01/0.05/0.1 SOL). For MNY, buyInLamports must be greater than 0 in MNY base units. status must initialize to 'waiting', creatorWins=0, opponentWins=0, currentRound=1, opponent=null, winner=null. lastActivityAt must equal createdAt on create. Hook creates per-match escrow PDA via @AccountPlugin.createAccount($matchId), ensures the appropriate fee-pool PDA exists (SPIN_POOL_ID for MNY, FEE_POOL_ID for SOL), and transfers buyInLamports from creator into the escrow in the correct token. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setRpsMatches(matchId: string, data: RpsMatchesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`rpsMatches/${matchId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting RpsMatches: ${formatError(error)}`);
    return false;
  }
}

export type RpsMatchesRequestUpdate = Partial<RpsMatchesRequest>;

/**
 * Build a RpsMatches update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateRpsMatches(matchId: string, data: RpsMatchesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `rpsMatches/${matchId}`, document: doc };
}

/**
 * Four transitions: (a) JOIN — a different user (not the creator) sets opponent=@user.address and status='waiting'->'active'; must set lastActivityAt=@time.now. Hook transfers matching buyInLamports from opponent into the escrow in the match's token (MNY or SOL). (b) ROUND PROGRESS — either player updates creatorWins/opponentWins/currentRound while status remains 'active'; must set lastActivityAt=@time.now. Each counter may only increment by 0 or 1 per update; currentRound may increment by 0 or 1. winner stays null and neither score may reach 2. No onchain transfer fires. (c) COMPLETE — either player flips status 'active'->'complete' when one side reaches 2 round wins; lastActivityAt is preserved (no change). winner must match the side that hit 2. Hook pays 99% of the pot (buyInLamports*2*99//100) from the escrow PDA to the winner and routes the 1% fee (buyInLamports*2*1//100) to the FEE_POOL_ID PDA (SOL) or SPIN_POOL_ID PDA (MNY) — consistent with coinflip fee routing. (d) ABANDON — any authenticated user (either player OR third party) flips status 'active'->'abandoned' once @time.now >= @data.lastActivityAt + RPS_ABANDON_TIMEOUT_SECONDS. All preserved fields must remain unchanged; winner must be null. Hook refunds @data.buyInLamports to BOTH creator and opponent from the escrow PDA in the original currency (MNY or SOL). creator/opponent/buyInLamports/buyInCurrency/createdAt are preserved across all updates. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateRpsMatches(matchId: string, data: RpsMatchesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`rpsMatches/${matchId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating RpsMatches: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read RPS matches. Used to list waiting matches (lobby), active matches (in-progress), complete matches (history), and abandoned matches (timed-out).
   (Get Single Item)
 */
export async function getRpsMatches(matchId: string): Promise<RpsMatchesResponse | null> {
  try {
    const result = await get(`rpsMatches/${matchId}`);
    return result as RpsMatchesResponse | null;
  } catch (error) {
    console.error(`Error getting RpsMatches: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single RpsMatches document. (
  Read Operation Details: Anyone can read RPS matches. Used to list waiting matches (lobby), active matches (in-progress), complete matches (history), and abandoned matches (timed-out).
  )
 */
export function subscribeRpsMatches(callback: (data: RpsMatchesResponse | null) => void, matchId: string): Promise<() => Promise<void>> {
  return subscribe(`rpsMatches/${matchId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as RpsMatchesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to RpsMatches at path '${`rpsMatches/${matchId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many RpsMatches items from collection rpsMatches
 
  Read Operation Details: Anyone can read RPS matches. Used to list waiting matches (lobby), active matches (in-progress), complete matches (history), and abandoned matches (timed-out).
  
 */
export async function getManyRpsMatches(filter: string = ""): Promise<RpsMatchesResponse[]> {
  try {
    const results = await get("rpsMatches", { prompt: filter });
    return Array.isArray(results) ? results as RpsMatchesResponse[] : [];
  } catch (error) {
    console.error(`Error getting RpsMatches collection at path 'rpsMatches': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in RpsMatches collection at rpsMatches
 
  Read Operation Details: Anyone can read RPS matches. Used to list waiting matches (lobby), active matches (in-progress), complete matches (history), and abandoned matches (timed-out).
  
 */
export function subscribeManyRpsMatches(callback: (data: RpsMatchesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("rpsMatches", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RpsMatchesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to RpsMatches collection at path '${"rpsMatches"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all RpsMatches items from collection rpsMatches
 
  Read Operation Details: Anyone can read RPS matches. Used to list waiting matches (lobby), active matches (in-progress), complete matches (history), and abandoned matches (timed-out).
  
 */
export async function getAllRpsMatches(filter: string = ""): Promise<RpsMatchesResponse[]> {
  try {
    const results = await get("rpsMatches", { prompt: filter });
    return Array.isArray(results) ? results as RpsMatchesResponse[] : [];
  } catch (error) {
    console.error(`Error getting RpsMatches collection at path 'rpsMatches': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in RpsMatches collection at rpsMatches
 
  Read Operation Details: Anyone can read RPS matches. Used to list waiting matches (lobby), active matches (in-progress), complete matches (history), and abandoned matches (timed-out).
  
 */
export function subscribeAllRpsMatches(callback: (data: RpsMatchesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("rpsMatches", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RpsMatchesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to RpsMatches collection at path '${"rpsMatches"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count RpsMatches items in collection rpsMatches.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countRpsMatches(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("rpsMatches", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting RpsMatches at path 'rpsMatches': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on RpsMatches items in collection rpsMatches.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateRpsMatches(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("rpsMatches", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating RpsMatches at path 'rpsMatches': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * 
  Delete Operation Details: Creator may delete (cancel) the match only while status='waiting' and no opponent has joined. Hook refunds the creator's buyInLamports from the escrow PDA in the original currency (MNY or SOL). Once an opponent joins, the match is non-deletable and must run to completion (or be abandoned after timeout).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteRpsMatches(matchId: string): Promise<boolean> {
  try {
    const succeeded = await set(`rpsMatches/${matchId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting RpsMatches: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for RpsMatches for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteRpsMatches(matchId: string): DocumentOperation {
  return { path: `rpsMatches/${matchId}`, document: null };
}

/**
 * Runs the "getMatchEscrowAddress" query on RpsMatches.
 * Query Logic: @AccountPlugin.getAccountAddress($matchId)
 */
export async function runGetMatchEscrowAddressQueryForRpsMatches(matchId: string, ): Promise<string> {
  try {
    const result = await runQuery(`rpsMatches/${matchId}`, "getMatchEscrowAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getMatchEscrowAddress" on RpsMatches: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getFeePoolAddress" query on RpsMatches.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.FEE_POOL_ID)
 */
export async function runGetFeePoolAddressQueryForRpsMatches(matchId: string, ): Promise<string> {
  try {
    const result = await runQuery(`rpsMatches/${matchId}`, "getFeePoolAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getFeePoolAddress" on RpsMatches: ${formatError(error)}`);
    throw error;
  }
}


/**
 * Offchain commit-reveal record for a single round of an RPS match. Each player first writes a hash of (move + nonce), then reveals the plaintext move and nonce after both commits are in. Once both reveals are present, either player can compute and set the winner ('creator' | 'opponent' | 'draw') and flip phase to 'complete'. Pure offchain coordination — no SOL movement here; pot is settled by the parent rpsMatches doc when one side reaches 2 round wins.
 */

export interface RpsMatchesRoundsRequest {
  creatorCommitHash?: string;
  opponentCommitHash?: string;
  creatorMove?: string;
  creatorNonce?: string;
  opponentMove?: string;
  opponentNonce?: string;
  winner?: string;
  phase: string;
}

export interface RpsMatchesRoundsResponse {
  creatorCommitHash?: string;
  opponentCommitHash?: string;
  creatorMove?: string;
  creatorNonce?: string;
  opponentMove?: string;
  opponentNonce?: string;
  winner?: string;
  phase: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a RpsMatchesRounds operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildRpsMatchesRounds(matchId: string, roundNumber: string, data: RpsMatchesRoundsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `rpsMatches/${matchId}/rounds/${roundNumber}`, document: doc };
}

/**
 * Either player of the parent rpsMatches doc (creator or opponent) creates a round row while the parent match status is 'active'. phase must initialize to 'committing' and all move/nonce/winner fields must start null. No onchain effect. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setRpsMatchesRounds(matchId: string, roundNumber: string, data: RpsMatchesRoundsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`rpsMatches/${matchId}/rounds/${roundNumber}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting RpsMatchesRounds: ${formatError(error)}`);
    return false;
  }
}

export type RpsMatchesRoundsRequestUpdate = Partial<RpsMatchesRoundsRequest>;

/**
 * Build a RpsMatchesRounds update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateRpsMatchesRounds(matchId: string, roundNumber: string, data: RpsMatchesRoundsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `rpsMatches/${matchId}/rounds/${roundNumber}`, document: doc };
}

/**
 * Four transitions, all gated to the two players of the parent match: (a) COMMIT — each player writes only their own commit hash (creatorCommitHash for creator, opponentCommitHash for opponent) while phase is 'committing'. (b) PHASE FLIP — either player flips phase 'committing'→'revealing' once both commit hashes are set. (c) REVEAL — each player writes only their own move + nonce (creatorMove/creatorNonce or opponentMove/opponentNonce) after their commit hash is set; opposing player's fields are untouched. (d) COMPLETE — once both reveals are present, either player sets winner ('creator' | 'opponent' | 'draw') and flips phase 'revealing'→'complete'. The parent rpsMatches doc score is updated separately by the players via its own update path. No onchain effect. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateRpsMatchesRounds(matchId: string, roundNumber: string, data: RpsMatchesRoundsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`rpsMatches/${matchId}/rounds/${roundNumber}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating RpsMatchesRounds: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read round commit/reveal records. Used to drive the per-round UI (waiting for opponent commit, waiting for reveals, showing final outcome).
   (Get Single Item)
 */
export async function getRpsMatchesRounds(matchId: string, roundNumber: string): Promise<RpsMatchesRoundsResponse | null> {
  try {
    const result = await get(`rpsMatches/${matchId}/rounds/${roundNumber}`);
    return result as RpsMatchesRoundsResponse | null;
  } catch (error) {
    console.error(`Error getting RpsMatchesRounds: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single RpsMatchesRounds document. (
  Read Operation Details: Anyone can read round commit/reveal records. Used to drive the per-round UI (waiting for opponent commit, waiting for reveals, showing final outcome).
  )
 */
export function subscribeRpsMatchesRounds(callback: (data: RpsMatchesRoundsResponse | null) => void, matchId: string, roundNumber: string): Promise<() => Promise<void>> {
  return subscribe(`rpsMatches/${matchId}/rounds/${roundNumber}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as RpsMatchesRoundsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to RpsMatchesRounds at path '${`rpsMatches/${matchId}/rounds/${roundNumber}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many RpsMatchesRounds items from collection rpsMatches/${matchId}/rounds
 
  Read Operation Details: Anyone can read round commit/reveal records. Used to drive the per-round UI (waiting for opponent commit, waiting for reveals, showing final outcome).
  
 */
export async function getManyRpsMatchesRounds(matchId: string, filter: string = ""): Promise<RpsMatchesRoundsResponse[]> {
  try {
    const results = await get(`rpsMatches/${matchId}/rounds`, { prompt: filter });
    return Array.isArray(results) ? results as RpsMatchesRoundsResponse[] : [];
  } catch (error) {
    console.error(`Error getting RpsMatchesRounds collection at path 'rpsMatches/${matchId}/rounds': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in RpsMatchesRounds collection at rpsMatches/${matchId}/rounds
 
  Read Operation Details: Anyone can read round commit/reveal records. Used to drive the per-round UI (waiting for opponent commit, waiting for reveals, showing final outcome).
  
 */
export function subscribeManyRpsMatchesRounds(callback: (data: RpsMatchesRoundsResponse[]) => void, matchId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`rpsMatches/${matchId}/rounds`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RpsMatchesRoundsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to RpsMatchesRounds collection at path '${`rpsMatches/${matchId}/rounds`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all RpsMatchesRounds items from collection rpsMatches/${matchId}/rounds
 
  Read Operation Details: Anyone can read round commit/reveal records. Used to drive the per-round UI (waiting for opponent commit, waiting for reveals, showing final outcome).
  
 */
export async function getAllRpsMatchesRounds(matchId: string, filter: string = ""): Promise<RpsMatchesRoundsResponse[]> {
  try {
    const results = await get(`rpsMatches/*/rounds`, { prompt: filter });
    return Array.isArray(results) ? results as RpsMatchesRoundsResponse[] : [];
  } catch (error) {
    console.error(`Error getting RpsMatchesRounds collection at path 'rpsMatches/${matchId}/rounds': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in RpsMatchesRounds collection at rpsMatches/${matchId}/rounds
 
  Read Operation Details: Anyone can read round commit/reveal records. Used to drive the per-round UI (waiting for opponent commit, waiting for reveals, showing final outcome).
  
 */
export function subscribeAllRpsMatchesRounds(callback: (data: RpsMatchesRoundsResponse[]) => void, matchId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`rpsMatches/*/rounds`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as RpsMatchesRoundsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to RpsMatchesRounds collection at path '${`rpsMatches/*/rounds`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count RpsMatchesRounds items in collection rpsMatches/${matchId}/rounds.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countRpsMatchesRounds(matchId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`rpsMatches/${matchId}/rounds`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting RpsMatchesRounds at path 'rpsMatches/${matchId}/rounds': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on RpsMatchesRounds items in collection rpsMatches/${matchId}/rounds.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateRpsMatchesRounds(matchId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`rpsMatches/${matchId}/rounds`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating RpsMatchesRounds at path 'rpsMatches/${matchId}/rounds': ${formatError(error)}`);
    return { value: 0 };
  }
}

