// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.455Z
// Collection: tokenUnlocks/$unlockId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Onchain token unlock records — each document represents one scheduled unlock trigger releasing 20% of total MNY supply from treasury to admin wallet. Only admin or backend can trigger.
 */

export interface TokenUnlocksRequest {
  triggeredBy: AddressType;
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  tranche: number | TimeOperation | IncrementOperation | TokenAmount;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
  milestoneId: string;
}

export interface TokenUnlocksResponse {
  triggeredBy: string;
  amount: number;
  tranche: number;
  ts: number;
  milestoneId: string;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a TokenUnlocks operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildTokenUnlocks(unlockId: string, data: TokenUnlocksRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `tokenUnlocks/${unlockId}`, document: doc };
}

/**
 * Only ADMIN_ADDRESS or PROJECT_VAULT_ADDRESS can trigger. Transfers 20% of total supply (TPR_INITIAL_SUPPLY / 5 = 200,000,000,000 base units = 200,000 MNY) from treasury PDA to admin wallet via @TokenPlugin.transfer. Idempotently initializes or increments tokenUnlockStats/main.totalUnlocked. Frontend must provide: triggeredBy (caller address), amount (TPR_INITIAL_SUPPLY // 5), tranche (sequential counter), ts (current Unix timestamp), milestoneId (one of 'second-sale', 'special-prizes-part-2', 'final-sale'). milestoneId is enforced via create rule. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setTokenUnlocks(unlockId: string, data: TokenUnlocksRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`tokenUnlocks/${unlockId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting TokenUnlocks: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read unlock records. Public transparency for all token releases.
   (Get Single Item)
 */
export async function getTokenUnlocks(unlockId: string): Promise<TokenUnlocksResponse | null> {
  try {
    const result = await get(`tokenUnlocks/${unlockId}`);
    return result as TokenUnlocksResponse | null;
  } catch (error) {
    console.error(`Error getting TokenUnlocks: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single TokenUnlocks document. (
  Read Operation Details: Anyone can read unlock records. Public transparency for all token releases.
  )
 */
export function subscribeTokenUnlocks(callback: (data: TokenUnlocksResponse | null) => void, unlockId: string): Promise<() => Promise<void>> {
  return subscribe(`tokenUnlocks/${unlockId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TokenUnlocksResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to TokenUnlocks at path '${`tokenUnlocks/${unlockId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many TokenUnlocks items from collection tokenUnlocks
 
  Read Operation Details: Anyone can read unlock records. Public transparency for all token releases.
  
 */
export async function getManyTokenUnlocks(filter: string = ""): Promise<TokenUnlocksResponse[]> {
  try {
    const results = await get("tokenUnlocks", { prompt: filter });
    return Array.isArray(results) ? results as TokenUnlocksResponse[] : [];
  } catch (error) {
    console.error(`Error getting TokenUnlocks collection at path 'tokenUnlocks': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TokenUnlocks collection at tokenUnlocks
 
  Read Operation Details: Anyone can read unlock records. Public transparency for all token releases.
  
 */
export function subscribeManyTokenUnlocks(callback: (data: TokenUnlocksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tokenUnlocks", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TokenUnlocksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TokenUnlocks collection at path '${"tokenUnlocks"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all TokenUnlocks items from collection tokenUnlocks
 
  Read Operation Details: Anyone can read unlock records. Public transparency for all token releases.
  
 */
export async function getAllTokenUnlocks(filter: string = ""): Promise<TokenUnlocksResponse[]> {
  try {
    const results = await get("tokenUnlocks", { prompt: filter });
    return Array.isArray(results) ? results as TokenUnlocksResponse[] : [];
  } catch (error) {
    console.error(`Error getting TokenUnlocks collection at path 'tokenUnlocks': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TokenUnlocks collection at tokenUnlocks
 
  Read Operation Details: Anyone can read unlock records. Public transparency for all token releases.
  
 */
export function subscribeAllTokenUnlocks(callback: (data: TokenUnlocksResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tokenUnlocks", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TokenUnlocksResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TokenUnlocks collection at path '${"tokenUnlocks"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count TokenUnlocks items in collection tokenUnlocks.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countTokenUnlocks(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("tokenUnlocks", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting TokenUnlocks at path 'tokenUnlocks': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on TokenUnlocks items in collection tokenUnlocks.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateTokenUnlocks(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("tokenUnlocks", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating TokenUnlocks at path 'tokenUnlocks': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getTreasuryAddress" query on TokenUnlocks.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.TPR_TREASURY_ID)
 */
export async function runGetTreasuryAddressQueryForTokenUnlocks(unlockId: string, ): Promise<string> {
  try {
    const result = await runQuery(`tokenUnlocks/${unlockId}`, "getTreasuryAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getTreasuryAddress" on TokenUnlocks: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getTokenMint" query on TokenUnlocks.
 * Query Logic: @TokenPlugin.getTokenMintAddress(@constants.TPR_TOKEN_ID, @constants.TPR_NAME, @constants.TPR_SYMBOL)
 */
export async function runGetTokenMintQueryForTokenUnlocks(unlockId: string, ): Promise<string> {
  try {
    const result = await runQuery(`tokenUnlocks/${unlockId}`, "getTokenMint", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getTokenMint" on TokenUnlocks: ${formatError(error)}`);
    throw error;
  }
}

