// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.456Z
// Collection: tprSalePrice/$id
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Onchain singleton (ID 'main') configurable by admin holding the current MNY primary-sale price in lamports of SOL per 1 whole MNY token (= 10^6 base units). If this document does not exist, the primary sale falls back to the constant TPR_PRIMARY_SALE_PRICE_LAMPORTS. Admin can update it at any time (e.g., at tranche unlock time) to change the price for subsequent purchases. No onchain hooks - metadata only.
 */

export interface TprSalePriceRequest {
  priceLamportsPerWholeToken: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TprSalePriceResponse {
  priceLamportsPerWholeToken: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a TprSalePrice operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildTprSalePrice(id: string, data?: TprSalePriceRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `tprSalePrice/${id}`, document: doc };
}

/**
 * Only ADMIN_ADDRESS can create the singleton document with ID 'main'. priceLamportsPerWholeToken must be > 0. Sets the active per-whole-token price for tprPrimarySales going forward. Field is readonly (UInt!) after create - use update to change the price. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setTprSalePrice(id: string, data?: TprSalePriceRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`tprSalePrice/${id}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting TprSalePrice: ${formatError(error)}`);
    return false;
  }
}

export type TprSalePriceRequestUpdate = Partial<TprSalePriceRequest>;

/**
 * Build a TprSalePrice update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateTprSalePrice(id: string, data: TprSalePriceRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `tprSalePrice/${id}`, document: doc };
}

/**
 * Only ADMIN_ADDRESS can update. priceLamportsPerWholeToken must be > 0. Allows admin to change the primary-sale price (e.g., at each new tranche unlock). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateTprSalePrice(id: string, data: TprSalePriceRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`tprSalePrice/${id}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating TprSalePrice: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read the current MNY primary-sale price. Public so frontends can compute SOL cost for a purchase.
   (Get Single Item)
 */
export async function getTprSalePrice(id: string): Promise<TprSalePriceResponse | null> {
  try {
    const result = await get(`tprSalePrice/${id}`);
    return result as TprSalePriceResponse | null;
  } catch (error) {
    console.error(`Error getting TprSalePrice: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single TprSalePrice document. (
  Read Operation Details: Anyone can read the current MNY primary-sale price. Public so frontends can compute SOL cost for a purchase.
  )
 */
export function subscribeTprSalePrice(callback: (data: TprSalePriceResponse | null) => void, id: string): Promise<() => Promise<void>> {
  return subscribe(`tprSalePrice/${id}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TprSalePriceResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to TprSalePrice at path '${`tprSalePrice/${id}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many TprSalePrice items from collection tprSalePrice
 
  Read Operation Details: Anyone can read the current MNY primary-sale price. Public so frontends can compute SOL cost for a purchase.
  
 */
export async function getManyTprSalePrice(filter: string = ""): Promise<TprSalePriceResponse[]> {
  try {
    const results = await get("tprSalePrice", { prompt: filter });
    return Array.isArray(results) ? results as TprSalePriceResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprSalePrice collection at path 'tprSalePrice': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprSalePrice collection at tprSalePrice
 
  Read Operation Details: Anyone can read the current MNY primary-sale price. Public so frontends can compute SOL cost for a purchase.
  
 */
export function subscribeManyTprSalePrice(callback: (data: TprSalePriceResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprSalePrice", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprSalePriceResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprSalePrice collection at path '${"tprSalePrice"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all TprSalePrice items from collection tprSalePrice
 
  Read Operation Details: Anyone can read the current MNY primary-sale price. Public so frontends can compute SOL cost for a purchase.
  
 */
export async function getAllTprSalePrice(filter: string = ""): Promise<TprSalePriceResponse[]> {
  try {
    const results = await get("tprSalePrice", { prompt: filter });
    return Array.isArray(results) ? results as TprSalePriceResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprSalePrice collection at path 'tprSalePrice': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprSalePrice collection at tprSalePrice
 
  Read Operation Details: Anyone can read the current MNY primary-sale price. Public so frontends can compute SOL cost for a purchase.
  
 */
export function subscribeAllTprSalePrice(callback: (data: TprSalePriceResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprSalePrice", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprSalePriceResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprSalePrice collection at path '${"tprSalePrice"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count TprSalePrice items in collection tprSalePrice.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countTprSalePrice(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("tprSalePrice", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting TprSalePrice at path 'tprSalePrice': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on TprSalePrice items in collection tprSalePrice.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateTprSalePrice(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("tprSalePrice", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating TprSalePrice at path 'tprSalePrice': ${formatError(error)}`);
    return { value: 0 };
  }
}

