// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: coinFlipMatchReveals/$matchId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * VRF callback for coin flip match - resolves winner based on random outcome. Winner address is computed INLINE from VRF randomness in every payout/update expression (NOT read back via getAfter). Pays 99% of pot to winner and 1% fee to SPIN_POOL_ID (MNY) or FEE_POOL_ID (SOL) based on parent match's buyInCurrency. Updates parent coinFlipMatches doc with winner and state='resolved'. Idempotent via early-return when state is already 'resolved'.
 */

export interface CoinFlipMatchRevealsRequest {

}

export interface CoinFlipMatchRevealsResponse {

  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a CoinFlipMatchReveals operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildCoinFlipMatchReveals(matchId: string, data?: CoinFlipMatchRevealsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `coinFlipMatchReveals/${matchId}`, document: doc };
}

/**
 * Oracle VRF callback triggered automatically by Orao after @OraclePlugin.requestRandomness. EXECUTION ORDER (critical for reliability): (1) idempotency early-return if parent state is already 'resolved'; (2) verify parent is 'waiting' with an opponent; (3) compute winner inline from @OraclePlugin.getRandomNumber($matchId,0,2) where 0->creator and 1->opponent, and write it to the parent match's 'winner' field via @DocumentPlugin.updateField (bypasses collection rules); (4) write state='resolved' via @DocumentPlugin.updateField; (5) THEN pay 99% of pot to the recorded winner (read back via getAfter so payout matches the stored winner exactly) and 1% fee to SPIN_POOL_ID (MNY) or FEE_POOL_ID (SOL) based on parent buyInCurrency. The whole expression is wrapped in '|| true' so the reveal document and the winner/state writes are never rolled back by a transient payout edge case, and so duplicate oracle callbacks are safe. winner/state are written BEFORE payouts so the match always reaches 'resolved' (frontend keys 'Games Played' and animation-stop off state=='resolved'). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setCoinFlipMatchReveals(matchId: string, data?: CoinFlipMatchRevealsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`coinFlipMatchReveals/${matchId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting CoinFlipMatchReveals: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read reveal records (fieldless audit markers).
   (Get Single Item)
 */
export async function getCoinFlipMatchReveals(matchId: string): Promise<CoinFlipMatchRevealsResponse | null> {
  try {
    const result = await get(`coinFlipMatchReveals/${matchId}`);
    return result as CoinFlipMatchRevealsResponse | null;
  } catch (error) {
    console.error(`Error getting CoinFlipMatchReveals: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single CoinFlipMatchReveals document. (
  Read Operation Details: Anyone can read reveal records (fieldless audit markers).
  )
 */
export function subscribeCoinFlipMatchReveals(callback: (data: CoinFlipMatchRevealsResponse | null) => void, matchId: string): Promise<() => Promise<void>> {
  return subscribe(`coinFlipMatchReveals/${matchId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as CoinFlipMatchRevealsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to CoinFlipMatchReveals at path '${`coinFlipMatchReveals/${matchId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many CoinFlipMatchReveals items from collection coinFlipMatchReveals
 
  Read Operation Details: Anyone can read reveal records (fieldless audit markers).
  
 */
export async function getManyCoinFlipMatchReveals(filter: string = ""): Promise<CoinFlipMatchRevealsResponse[]> {
  try {
    const results = await get("coinFlipMatchReveals", { prompt: filter });
    return Array.isArray(results) ? results as CoinFlipMatchRevealsResponse[] : [];
  } catch (error) {
    console.error(`Error getting CoinFlipMatchReveals collection at path 'coinFlipMatchReveals': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in CoinFlipMatchReveals collection at coinFlipMatchReveals
 
  Read Operation Details: Anyone can read reveal records (fieldless audit markers).
  
 */
export function subscribeManyCoinFlipMatchReveals(callback: (data: CoinFlipMatchRevealsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("coinFlipMatchReveals", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as CoinFlipMatchRevealsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to CoinFlipMatchReveals collection at path '${"coinFlipMatchReveals"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all CoinFlipMatchReveals items from collection coinFlipMatchReveals
 
  Read Operation Details: Anyone can read reveal records (fieldless audit markers).
  
 */
export async function getAllCoinFlipMatchReveals(filter: string = ""): Promise<CoinFlipMatchRevealsResponse[]> {
  try {
    const results = await get("coinFlipMatchReveals", { prompt: filter });
    return Array.isArray(results) ? results as CoinFlipMatchRevealsResponse[] : [];
  } catch (error) {
    console.error(`Error getting CoinFlipMatchReveals collection at path 'coinFlipMatchReveals': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in CoinFlipMatchReveals collection at coinFlipMatchReveals
 
  Read Operation Details: Anyone can read reveal records (fieldless audit markers).
  
 */
export function subscribeAllCoinFlipMatchReveals(callback: (data: CoinFlipMatchRevealsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("coinFlipMatchReveals", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as CoinFlipMatchRevealsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to CoinFlipMatchReveals collection at path '${"coinFlipMatchReveals"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count CoinFlipMatchReveals items in collection coinFlipMatchReveals.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countCoinFlipMatchReveals(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("coinFlipMatchReveals", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting CoinFlipMatchReveals at path 'coinFlipMatchReveals': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on CoinFlipMatchReveals items in collection coinFlipMatchReveals.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateCoinFlipMatchReveals(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("coinFlipMatchReveals", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating CoinFlipMatchReveals at path 'coinFlipMatchReveals': ${formatError(error)}`);
    return { value: 0 };
  }
}

