// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: coinFlipMatches/$matchId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * 1v1 coin flip match. Player 1 creates with a chosen buy-in tier (0.01, 0.05, or 0.1 SOL) and pays into a per-match escrow PDA. Player 2 joins by matching the buy-in; joining triggers VRF randomness. Winner takes 99% of the pot, 1% goes to the FEE_POOL_ID PDA. If no opponent joins, the match can be cancelled (by creator or by backend timeout cron) and the creator is refunded. Status transitions: waiting -> resolved, or waiting -> cancelled.
 */

export interface CoinFlipMatchesRequest {
  creator: AddressType;
  opponent?: AddressType;
  tier: number | TimeOperation | IncrementOperation | TokenAmount;
  buyIn: number | TimeOperation | IncrementOperation | TokenAmount;
  state: string;
  winner?: AddressType;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
  buyInCurrency: string;
}

export interface CoinFlipMatchesResponse {
  creator: string;
  opponent?: string;
  tier: number;
  buyIn: number;
  state: string;
  winner?: string;
  ts: number;
  buyInCurrency: string;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a CoinFlipMatches operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildCoinFlipMatches(matchId: string, data: CoinFlipMatchesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `coinFlipMatches/${matchId}`, document: doc };
}

/**
 * Any authenticated non-vault user creates a 1v1 match. Creator becomes player 1. Must specify buyInCurrency ('SOL' or 'MNY'). For SOL, must specify tier (1, 2, or 3) and matching buyIn value from constants (COINFLIP_TIER1_LAMPORTS=0.01 SOL, COINFLIP_TIER2_LAMPORTS=0.05 SOL, COINFLIP_TIER3_LAMPORTS=0.1 SOL). For MNY, buyIn must be greater than 0 in MNY base units. State must initialize to 'waiting' with opponent=null and winner=null. Hook creates per-match escrow PDA, ensures the appropriate pool PDA exists (SPIN_POOL_ID for MNY, FEE_POOL_ID for SOL), and transfers buyIn from creator to escrow. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setCoinFlipMatches(matchId: string, data: CoinFlipMatchesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`coinFlipMatches/${matchId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting CoinFlipMatches: ${formatError(error)}`);
    return false;
  }
}

export type CoinFlipMatchesRequestUpdate = Partial<CoinFlipMatchesRequest>;

/**
 * Build a CoinFlipMatches update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateCoinFlipMatches(matchId: string, data: CoinFlipMatchesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `coinFlipMatches/${matchId}`, document: doc };
}

/**
 * Three transitions: (a) JOIN — non-vault user (not the creator) joins by setting opponent=@user.address while state stays 'waiting'. Hook transfers matching buyIn from opponent to escrow and calls @OraclePlugin.requestRandomness. Currency-aware: SOL or MNY transfer based on match's buyInCurrency. (b) RESOLVE — backend (PROJECT_VAULT_ADDRESS) sets state='resolved' once opponent is present and winner is set (must be creator or opponent). Hook pays 99% of pot to winner and 1% fee to SPIN_POOL_ID (MNY) or FEE_POOL_ID (SOL). (c) CANCEL — either the creator (player-initiated) or PROJECT_VAULT_ADDRESS (cron timeout) sets state='cancelled' while opponent is still null. Hook refunds the full buyIn from escrow back to the creator in the original currency. ts/tier/buyIn/creator/buyInCurrency are preserved; opponent and winner remain null. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateCoinFlipMatches(matchId: string, data: CoinFlipMatchesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`coinFlipMatches/${matchId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating CoinFlipMatches: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read matches. Use to list waiting matches (state='waiting') for the lobby, resolved matches (state='resolved') for history, and cancelled matches (state='cancelled') for cancellation history.
   (Get Single Item)
 */
export async function getCoinFlipMatches(matchId: string): Promise<CoinFlipMatchesResponse | null> {
  try {
    const result = await get(`coinFlipMatches/${matchId}`);
    return result as CoinFlipMatchesResponse | null;
  } catch (error) {
    console.error(`Error getting CoinFlipMatches: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single CoinFlipMatches document. (
  Read Operation Details: Anyone can read matches. Use to list waiting matches (state='waiting') for the lobby, resolved matches (state='resolved') for history, and cancelled matches (state='cancelled') for cancellation history.
  )
 */
export function subscribeCoinFlipMatches(callback: (data: CoinFlipMatchesResponse | null) => void, matchId: string): Promise<() => Promise<void>> {
  return subscribe(`coinFlipMatches/${matchId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as CoinFlipMatchesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to CoinFlipMatches at path '${`coinFlipMatches/${matchId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many CoinFlipMatches items from collection coinFlipMatches
 
  Read Operation Details: Anyone can read matches. Use to list waiting matches (state='waiting') for the lobby, resolved matches (state='resolved') for history, and cancelled matches (state='cancelled') for cancellation history.
  
 */
export async function getManyCoinFlipMatches(filter: string = ""): Promise<CoinFlipMatchesResponse[]> {
  try {
    const results = await get("coinFlipMatches", { prompt: filter });
    return Array.isArray(results) ? results as CoinFlipMatchesResponse[] : [];
  } catch (error) {
    console.error(`Error getting CoinFlipMatches collection at path 'coinFlipMatches': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in CoinFlipMatches collection at coinFlipMatches
 
  Read Operation Details: Anyone can read matches. Use to list waiting matches (state='waiting') for the lobby, resolved matches (state='resolved') for history, and cancelled matches (state='cancelled') for cancellation history.
  
 */
export function subscribeManyCoinFlipMatches(callback: (data: CoinFlipMatchesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("coinFlipMatches", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as CoinFlipMatchesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to CoinFlipMatches collection at path '${"coinFlipMatches"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all CoinFlipMatches items from collection coinFlipMatches
 
  Read Operation Details: Anyone can read matches. Use to list waiting matches (state='waiting') for the lobby, resolved matches (state='resolved') for history, and cancelled matches (state='cancelled') for cancellation history.
  
 */
export async function getAllCoinFlipMatches(filter: string = ""): Promise<CoinFlipMatchesResponse[]> {
  try {
    const results = await get("coinFlipMatches", { prompt: filter });
    return Array.isArray(results) ? results as CoinFlipMatchesResponse[] : [];
  } catch (error) {
    console.error(`Error getting CoinFlipMatches collection at path 'coinFlipMatches': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in CoinFlipMatches collection at coinFlipMatches
 
  Read Operation Details: Anyone can read matches. Use to list waiting matches (state='waiting') for the lobby, resolved matches (state='resolved') for history, and cancelled matches (state='cancelled') for cancellation history.
  
 */
export function subscribeAllCoinFlipMatches(callback: (data: CoinFlipMatchesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("coinFlipMatches", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as CoinFlipMatchesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to CoinFlipMatches collection at path '${"coinFlipMatches"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count CoinFlipMatches items in collection coinFlipMatches.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countCoinFlipMatches(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("coinFlipMatches", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting CoinFlipMatches at path 'coinFlipMatches': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on CoinFlipMatches items in collection coinFlipMatches.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateCoinFlipMatches(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("coinFlipMatches", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating CoinFlipMatches at path 'coinFlipMatches': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getMatchEscrowAddress" query on CoinFlipMatches.
 * Query Logic: @AccountPlugin.getAccountAddress($matchId)
 */
export async function runGetMatchEscrowAddressQueryForCoinFlipMatches(matchId: string, ): Promise<string> {
  try {
    const result = await runQuery(`coinFlipMatches/${matchId}`, "getMatchEscrowAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getMatchEscrowAddress" on CoinFlipMatches: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getFeePoolAddress" query on CoinFlipMatches.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.FEE_POOL_ID)
 */
export async function runGetFeePoolAddressQueryForCoinFlipMatches(matchId: string, ): Promise<string> {
  try {
    const result = await runQuery(`coinFlipMatches/${matchId}`, "getFeePoolAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getFeePoolAddress" on CoinFlipMatches: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getRandomOutcome" query on CoinFlipMatches.
 * Query Logic: @OraclePlugin.getRandomNumber($matchId, 0, 2)
 */
export async function runGetRandomOutcomeQueryForCoinFlipMatches(matchId: string, ): Promise<number> {
  try {
    const result = await runQuery(`coinFlipMatches/${matchId}`, "getRandomOutcome", {});
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "getRandomOutcome" on CoinFlipMatches: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getVRFAddress" query on CoinFlipMatches.
 * Query Logic: @OraclePlugin.getVRFAddress($matchId)
 */
export async function runGetVRFAddressQueryForCoinFlipMatches(matchId: string, ): Promise<string> {
  try {
    const result = await runQuery(`coinFlipMatches/${matchId}`, "getVRFAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getVRFAddress" on CoinFlipMatches: ${formatError(error)}`);
    throw error;
  }
}

