// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.399Z
// Collection: dailySpinPool/$id
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Singleton tracking the daily spin prize pool metadata in MNY. The actual MNY tokens live in the SPIN_POOL_ID PDA escrow; this collection tracks balance, total distributed, spin count, and last update timestamp. Onchain to support the getSpinPoolAddress query.
 */

export interface DailySpinPoolRequest {
  balance: number | TimeOperation | IncrementOperation | TokenAmount;
  totalDistributed: number | TimeOperation | IncrementOperation | TokenAmount;
  spinCount: number | TimeOperation | IncrementOperation | TokenAmount;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface DailySpinPoolResponse {
  balance: number;
  totalDistributed: number;
  spinCount: number;
  ts: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a DailySpinPool operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDailySpinPool(id: string, data: DailySpinPoolRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `dailySpinPool/${id}`, document: doc };
}

/**
 * Backend vault (PROJECT_VAULT_ADDRESS) or ADMIN_ADDRESS. Initializes the singleton spin pool tracker. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setDailySpinPool(id: string, data: DailySpinPoolRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`dailySpinPool/${id}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting DailySpinPool: ${formatError(error)}`);
    return false;
  }
}

export type DailySpinPoolRequestUpdate = Partial<DailySpinPoolRequest>;

/**
 * Build a DailySpinPool update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateDailySpinPool(id: string, data: DailySpinPoolRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `dailySpinPool/${id}`, document: doc };
}

/**
 * Backend vault (PROJECT_VAULT_ADDRESS) for normal spin operations, or ADMIN_ADDRESS (directly or via the seedSpinPool seeding hook) to bump the balance when topping up the prize pool. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateDailySpinPool(id: string, data: DailySpinPoolRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`dailySpinPool/${id}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating DailySpinPool: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read the spin pool metadata (balance, totalDistributed, spinCount, ts).
   (Get Single Item)
 */
export async function getDailySpinPool(id: string): Promise<DailySpinPoolResponse | null> {
  try {
    const result = await get(`dailySpinPool/${id}`);
    return result as DailySpinPoolResponse | null;
  } catch (error) {
    console.error(`Error getting DailySpinPool: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single DailySpinPool document. (
  Read Operation Details: Anyone can read the spin pool metadata (balance, totalDistributed, spinCount, ts).
  )
 */
export function subscribeDailySpinPool(callback: (data: DailySpinPoolResponse | null) => void, id: string): Promise<() => Promise<void>> {
  return subscribe(`dailySpinPool/${id}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as DailySpinPoolResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to DailySpinPool at path '${`dailySpinPool/${id}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many DailySpinPool items from collection dailySpinPool
 
  Read Operation Details: Anyone can read the spin pool metadata (balance, totalDistributed, spinCount, ts).
  
 */
export async function getManyDailySpinPool(filter: string = ""): Promise<DailySpinPoolResponse[]> {
  try {
    const results = await get("dailySpinPool", { prompt: filter });
    return Array.isArray(results) ? results as DailySpinPoolResponse[] : [];
  } catch (error) {
    console.error(`Error getting DailySpinPool collection at path 'dailySpinPool': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in DailySpinPool collection at dailySpinPool
 
  Read Operation Details: Anyone can read the spin pool metadata (balance, totalDistributed, spinCount, ts).
  
 */
export function subscribeManyDailySpinPool(callback: (data: DailySpinPoolResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("dailySpinPool", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DailySpinPoolResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to DailySpinPool collection at path '${"dailySpinPool"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all DailySpinPool items from collection dailySpinPool
 
  Read Operation Details: Anyone can read the spin pool metadata (balance, totalDistributed, spinCount, ts).
  
 */
export async function getAllDailySpinPool(filter: string = ""): Promise<DailySpinPoolResponse[]> {
  try {
    const results = await get("dailySpinPool", { prompt: filter });
    return Array.isArray(results) ? results as DailySpinPoolResponse[] : [];
  } catch (error) {
    console.error(`Error getting DailySpinPool collection at path 'dailySpinPool': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in DailySpinPool collection at dailySpinPool
 
  Read Operation Details: Anyone can read the spin pool metadata (balance, totalDistributed, spinCount, ts).
  
 */
export function subscribeAllDailySpinPool(callback: (data: DailySpinPoolResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("dailySpinPool", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DailySpinPoolResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to DailySpinPool collection at path '${"dailySpinPool"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count DailySpinPool items in collection dailySpinPool.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countDailySpinPool(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("dailySpinPool", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting DailySpinPool at path 'dailySpinPool': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on DailySpinPool items in collection dailySpinPool.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateDailySpinPool(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("dailySpinPool", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating DailySpinPool at path 'dailySpinPool': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getSpinPoolAddress" query on DailySpinPool.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.SPIN_POOL_ID)
 */
export async function runGetSpinPoolAddressQueryForDailySpinPool(id: string, ): Promise<string> {
  try {
    const result = await runQuery(`dailySpinPool/${id}`, "getSpinPoolAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getSpinPoolAddress" on DailySpinPool: ${formatError(error)}`);
    throw error;
  }
}

