// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.399Z
// Collection: dailySpins/$userAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Tracks per-user daily spin state for cooldown enforcement and cumulative winnings in MNY. Off-chain only.
 */

export interface DailySpinsRequest {
  lastSpinAt: number | TimeOperation | IncrementOperation | TokenAmount;
  totalWon: number | TimeOperation | IncrementOperation | TokenAmount;
  spinCount: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface DailySpinsResponse {
  lastSpinAt: number;
  totalWon: number;
  spinCount: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a DailySpins operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDailySpins(userAddress: string, data: DailySpinsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `dailySpins/${userAddress}`, document: doc };
}

/**
 * Users create their own spin record on first spin. Backend (PROJECT_VAULT_ADDRESS) can also create on user's behalf via /api/daily-spin route. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setDailySpins(userAddress: string, data: DailySpinsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`dailySpins/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting DailySpins: ${formatError(error)}`);
    return false;
  }
}

export type DailySpinsRequestUpdate = Partial<DailySpinsRequest>;

/**
 * Build a DailySpins update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateDailySpins(userAddress: string, data: DailySpinsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `dailySpins/${userAddress}`, document: doc };
}

/**
 * Users update their own spin record after each spin (lastSpinAt, totalWon, spinCount). Backend (PROJECT_VAULT_ADDRESS) can also update via /api/daily-spin route. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateDailySpins(userAddress: string, data: DailySpinsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`dailySpins/${userAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating DailySpins: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Users can read their own spin record. Backend (PROJECT_VAULT_ADDRESS) can also read for /api/daily-spin route.
   (Get Single Item)
 */
export async function getDailySpins(userAddress: string): Promise<DailySpinsResponse | null> {
  try {
    const result = await get(`dailySpins/${userAddress}`);
    return result as DailySpinsResponse | null;
  } catch (error) {
    console.error(`Error getting DailySpins: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single DailySpins document. (
  Read Operation Details: Users can read their own spin record. Backend (PROJECT_VAULT_ADDRESS) can also read for /api/daily-spin route.
  )
 */
export function subscribeDailySpins(callback: (data: DailySpinsResponse | null) => void, userAddress: string): Promise<() => Promise<void>> {
  return subscribe(`dailySpins/${userAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as DailySpinsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to DailySpins at path '${`dailySpins/${userAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many DailySpins items from collection dailySpins
 
  Read Operation Details: Users can read their own spin record. Backend (PROJECT_VAULT_ADDRESS) can also read for /api/daily-spin route.
  
 */
export async function getManyDailySpins(filter: string = ""): Promise<DailySpinsResponse[]> {
  try {
    const results = await get("dailySpins", { prompt: filter });
    return Array.isArray(results) ? results as DailySpinsResponse[] : [];
  } catch (error) {
    console.error(`Error getting DailySpins collection at path 'dailySpins': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in DailySpins collection at dailySpins
 
  Read Operation Details: Users can read their own spin record. Backend (PROJECT_VAULT_ADDRESS) can also read for /api/daily-spin route.
  
 */
export function subscribeManyDailySpins(callback: (data: DailySpinsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("dailySpins", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DailySpinsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to DailySpins collection at path '${"dailySpins"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all DailySpins items from collection dailySpins
 
  Read Operation Details: Users can read their own spin record. Backend (PROJECT_VAULT_ADDRESS) can also read for /api/daily-spin route.
  
 */
export async function getAllDailySpins(filter: string = ""): Promise<DailySpinsResponse[]> {
  try {
    const results = await get("dailySpins", { prompt: filter });
    return Array.isArray(results) ? results as DailySpinsResponse[] : [];
  } catch (error) {
    console.error(`Error getting DailySpins collection at path 'dailySpins': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in DailySpins collection at dailySpins
 
  Read Operation Details: Users can read their own spin record. Backend (PROJECT_VAULT_ADDRESS) can also read for /api/daily-spin route.
  
 */
export function subscribeAllDailySpins(callback: (data: DailySpinsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("dailySpins", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as DailySpinsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to DailySpins collection at path '${"dailySpins"}': ${formatError(error)}`);
    }
  });
}

