// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: feePoolDistributions/$distributionId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Hourly fee-pool distribution records. Backend (PROJECT_VAULT_ADDRESS) creates one record per active staker per hour, which atomically transfers their pro-rata share of SOL from the FEE_POOL_ID PDA to the recipient. Distribution is based on the recipient's staked MNY (mnyStakes.amountStaked) at snapshot time. Pure MNY holders do NOT earn — only stakers earn. Document ID convention: '{epochHour}_{recipient}' so it is unique per recipient per hour.
 */

export interface FeePoolDistributionsRequest {
  epochHour: number | TimeOperation | IncrementOperation | TokenAmount;
  recipient: AddressType;
  amountLamports: number | TimeOperation | IncrementOperation | TokenAmount;
  totalPoolLamports: number | TimeOperation | IncrementOperation | TokenAmount;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
  stakedAmountBaseUnits: number | TimeOperation | IncrementOperation | TokenAmount;
  totalStakedAmountBaseUnits: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface FeePoolDistributionsResponse {
  epochHour: number;
  recipient: string;
  amountLamports: number;
  totalPoolLamports: number;
  ts: number;
  stakedAmountBaseUnits: number;
  totalStakedAmountBaseUnits: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a FeePoolDistributions operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFeePoolDistributions(distributionId: string, data?: FeePoolDistributionsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `feePoolDistributions/${distributionId}`, document: doc };
}

/**
 * Backend-only (PROJECT_VAULT_ADDRESS). Triggered by the Heartbeat hourly task. The backend snapshots all mnyStakes documents with amountStaked > 0, sums them into totalStakedAmountBaseUnits, computes each staker's share = totalPoolLamports * stakedAmountBaseUnits / totalStakedAmountBaseUnits, and writes one record per (epochHour, staker). Hook transfers SOL from FEE_POOL_ID PDA to the recipient atomically. Backend ensures the sum of distributions for an epochHour does not exceed the available pool balance. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFeePoolDistributions(distributionId: string, data?: FeePoolDistributionsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`feePoolDistributions/${distributionId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting FeePoolDistributions: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read distribution records. Public stats (total SOL distributed) are computed by summing amountLamports across this collection. Per-recipient history can be filtered client-side.
   (Get Single Item)
 */
export async function getFeePoolDistributions(distributionId: string): Promise<FeePoolDistributionsResponse | null> {
  try {
    const result = await get(`feePoolDistributions/${distributionId}`);
    return result as FeePoolDistributionsResponse | null;
  } catch (error) {
    console.error(`Error getting FeePoolDistributions: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single FeePoolDistributions document. (
  Read Operation Details: Anyone can read distribution records. Public stats (total SOL distributed) are computed by summing amountLamports across this collection. Per-recipient history can be filtered client-side.
  )
 */
export function subscribeFeePoolDistributions(callback: (data: FeePoolDistributionsResponse | null) => void, distributionId: string): Promise<() => Promise<void>> {
  return subscribe(`feePoolDistributions/${distributionId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FeePoolDistributionsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to FeePoolDistributions at path '${`feePoolDistributions/${distributionId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many FeePoolDistributions items from collection feePoolDistributions
 
  Read Operation Details: Anyone can read distribution records. Public stats (total SOL distributed) are computed by summing amountLamports across this collection. Per-recipient history can be filtered client-side.
  
 */
export async function getManyFeePoolDistributions(filter: string = ""): Promise<FeePoolDistributionsResponse[]> {
  try {
    const results = await get("feePoolDistributions", { prompt: filter });
    return Array.isArray(results) ? results as FeePoolDistributionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting FeePoolDistributions collection at path 'feePoolDistributions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FeePoolDistributions collection at feePoolDistributions
 
  Read Operation Details: Anyone can read distribution records. Public stats (total SOL distributed) are computed by summing amountLamports across this collection. Per-recipient history can be filtered client-side.
  
 */
export function subscribeManyFeePoolDistributions(callback: (data: FeePoolDistributionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("feePoolDistributions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FeePoolDistributionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FeePoolDistributions collection at path '${"feePoolDistributions"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all FeePoolDistributions items from collection feePoolDistributions
 
  Read Operation Details: Anyone can read distribution records. Public stats (total SOL distributed) are computed by summing amountLamports across this collection. Per-recipient history can be filtered client-side.
  
 */
export async function getAllFeePoolDistributions(filter: string = ""): Promise<FeePoolDistributionsResponse[]> {
  try {
    const results = await get("feePoolDistributions", { prompt: filter });
    return Array.isArray(results) ? results as FeePoolDistributionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting FeePoolDistributions collection at path 'feePoolDistributions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FeePoolDistributions collection at feePoolDistributions
 
  Read Operation Details: Anyone can read distribution records. Public stats (total SOL distributed) are computed by summing amountLamports across this collection. Per-recipient history can be filtered client-side.
  
 */
export function subscribeAllFeePoolDistributions(callback: (data: FeePoolDistributionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("feePoolDistributions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FeePoolDistributionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FeePoolDistributions collection at path '${"feePoolDistributions"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count FeePoolDistributions items in collection feePoolDistributions.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countFeePoolDistributions(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("feePoolDistributions", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting FeePoolDistributions at path 'feePoolDistributions': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on FeePoolDistributions items in collection feePoolDistributions.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateFeePoolDistributions(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("feePoolDistributions", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating FeePoolDistributions at path 'feePoolDistributions': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getFeePoolAddress" query on FeePoolDistributions.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.FEE_POOL_ID)
 */
export async function runGetFeePoolAddressQueryForFeePoolDistributions(distributionId: string, ): Promise<string> {
  try {
    const result = await runQuery(`feePoolDistributions/${distributionId}`, "getFeePoolAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getFeePoolAddress" on FeePoolDistributions: ${formatError(error)}`);
    throw error;
  }
}

