// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: flashMatchJoins/$matchId/players/$playerAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Per-player join records for a flash match. Each row represents a player who paid the buy-in into the match escrow PDA. Used by the backend to enumerate participants and validate winner address. The match creator's record is implied by the parent flashMatches.creator field; subsequent joiners create rows here.
 */

export interface FlashMatchJoinsPlayersRequest {
  player: AddressType;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface FlashMatchJoinsPlayersResponse {
  player: string;
  ts: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a FlashMatchJoinsPlayers operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFlashMatchJoinsPlayers(matchId: string, playerAddress: string, data?: FlashMatchJoinsPlayersRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `flashMatchJoins/${matchId}/players/${playerAddress}`, document: doc };
}

/**
 * Authenticated player joins a waiting match. $playerAddress must equal @user.address. Match must exist, be in 'waiting' state, have playerCount < MAX_PLAYERS_PER_MATCH (4), and the joiner must not already be the creator. Hook transfers buyIn (read from parent match) from joiner to match escrow PDA in the match's token (MNY or SOL) and increments flashMatches.playerCount. Path uniqueness on $playerAddress prevents the same wallet joining twice. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFlashMatchJoinsPlayers(matchId: string, playerAddress: string, data?: FlashMatchJoinsPlayersRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`flashMatchJoins/${matchId}/players/${playerAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting FlashMatchJoinsPlayers: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read participants (publicly verifiable).
   (Get Single Item)
 */
export async function getFlashMatchJoinsPlayers(matchId: string, playerAddress: string): Promise<FlashMatchJoinsPlayersResponse | null> {
  try {
    const result = await get(`flashMatchJoins/${matchId}/players/${playerAddress}`);
    return result as FlashMatchJoinsPlayersResponse | null;
  } catch (error) {
    console.error(`Error getting FlashMatchJoinsPlayers: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single FlashMatchJoinsPlayers document. (
  Read Operation Details: Anyone can read participants (publicly verifiable).
  )
 */
export function subscribeFlashMatchJoinsPlayers(callback: (data: FlashMatchJoinsPlayersResponse | null) => void, matchId: string, playerAddress: string): Promise<() => Promise<void>> {
  return subscribe(`flashMatchJoins/${matchId}/players/${playerAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FlashMatchJoinsPlayersResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to FlashMatchJoinsPlayers at path '${`flashMatchJoins/${matchId}/players/${playerAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many FlashMatchJoinsPlayers items from collection flashMatchJoins/${matchId}/players
 
  Read Operation Details: Anyone can read participants (publicly verifiable).
  
 */
export async function getManyFlashMatchJoinsPlayers(matchId: string, filter: string = ""): Promise<FlashMatchJoinsPlayersResponse[]> {
  try {
    const results = await get(`flashMatchJoins/${matchId}/players`, { prompt: filter });
    return Array.isArray(results) ? results as FlashMatchJoinsPlayersResponse[] : [];
  } catch (error) {
    console.error(`Error getting FlashMatchJoinsPlayers collection at path 'flashMatchJoins/${matchId}/players': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FlashMatchJoinsPlayers collection at flashMatchJoins/${matchId}/players
 
  Read Operation Details: Anyone can read participants (publicly verifiable).
  
 */
export function subscribeManyFlashMatchJoinsPlayers(callback: (data: FlashMatchJoinsPlayersResponse[]) => void, matchId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`flashMatchJoins/${matchId}/players`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FlashMatchJoinsPlayersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FlashMatchJoinsPlayers collection at path '${`flashMatchJoins/${matchId}/players`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all FlashMatchJoinsPlayers items from collection flashMatchJoins/${matchId}/players
 
  Read Operation Details: Anyone can read participants (publicly verifiable).
  
 */
export async function getAllFlashMatchJoinsPlayers(matchId: string, filter: string = ""): Promise<FlashMatchJoinsPlayersResponse[]> {
  try {
    const results = await get(`flashMatchJoins/*/players`, { prompt: filter });
    return Array.isArray(results) ? results as FlashMatchJoinsPlayersResponse[] : [];
  } catch (error) {
    console.error(`Error getting FlashMatchJoinsPlayers collection at path 'flashMatchJoins/${matchId}/players': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FlashMatchJoinsPlayers collection at flashMatchJoins/${matchId}/players
 
  Read Operation Details: Anyone can read participants (publicly verifiable).
  
 */
export function subscribeAllFlashMatchJoinsPlayers(callback: (data: FlashMatchJoinsPlayersResponse[]) => void, matchId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`flashMatchJoins/*/players`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FlashMatchJoinsPlayersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FlashMatchJoinsPlayers collection at path '${`flashMatchJoins/*/players`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count FlashMatchJoinsPlayers items in collection flashMatchJoins/${matchId}/players.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countFlashMatchJoinsPlayers(matchId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`flashMatchJoins/${matchId}/players`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting FlashMatchJoinsPlayers at path 'flashMatchJoins/${matchId}/players': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on FlashMatchJoinsPlayers items in collection flashMatchJoins/${matchId}/players.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateFlashMatchJoinsPlayers(matchId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`flashMatchJoins/${matchId}/players`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating FlashMatchJoinsPlayers at path 'flashMatchJoins/${matchId}/players': ${formatError(error)}`);
    return { value: 0 };
  }
}

