// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: flashMatches/$matchId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Flash-reaction game match. Up to 4 players each pay a tiered buy-in into a per-match escrow PDA. Backend chooses a flash time, players tap, and the backend resolves the match - 75% to winner, 20% to second place, 5% to fee pool PDA. If no other players have joined (playerCount == 1), the match can be cancelled by either the creator or PROJECT_VAULT_ADDRESS (cron timeout), and the creator's buy-in is refunded from the escrow PDA.
 */

export interface FlashMatchesRequest {
  creator: AddressType;
  playerCount: number | TimeOperation | IncrementOperation | TokenAmount;
  state: string;
  flashMomentMs: number | TimeOperation | IncrementOperation | TokenAmount;
  winner?: AddressType;
  winnerDeltaMs: number | TimeOperation | IncrementOperation | TokenAmount;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
  secondPlace?: AddressType;
  secondPlaceDeltaMs: number | TimeOperation | IncrementOperation | TokenAmount;
  buyIn: number | TimeOperation | IncrementOperation | TokenAmount;
  buyInCurrency: string;
}

export interface FlashMatchesResponse {
  creator: string;
  playerCount: number;
  state: string;
  flashMomentMs: number;
  winner?: string;
  winnerDeltaMs: number;
  ts: number;
  secondPlace?: string;
  secondPlaceDeltaMs: number;
  buyIn: number;
  buyInCurrency: string;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a FlashMatches operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFlashMatches(matchId: string, data: FlashMatchesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `flashMatches/${matchId}`, document: doc };
}

/**
 * Any authenticated non-vault user creates a match. Creator becomes player 1, transfers buyIn to a per-match escrow PDA derived from $matchId. Must specify buyInCurrency ('SOL' or 'MNY'). For SOL, buyIn must be one of: 10000000 (0.01 SOL Casual), 100000000 (0.1 SOL Standard), or 500000000 (0.5 SOL High Stakes). For MNY, buyIn must be greater than 0 in MNY base units. State must initialize to 'waiting'. Hook ensures the appropriate pool PDA exists (SPIN_POOL_ID for MNY, FEE_POOL_ID for SOL) and transfers buyIn from creator to escrow in the correct token. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFlashMatches(matchId: string, data: FlashMatchesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`flashMatches/${matchId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting FlashMatches: ${formatError(error)}`);
    return false;
  }
}

export type FlashMatchesRequestUpdate = Partial<FlashMatchesRequest>;

/**
 * Build a FlashMatches update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateFlashMatches(matchId: string, data: FlashMatchesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `flashMatches/${matchId}`, document: doc };
}

/**
 * Three transitions: (a) START: 'waiting' -> 'playing', backend-only (PROJECT_VAULT_ADDRESS). Backend has chosen flashMomentMs and writes it. playerCount, buyIn, and buyInCurrency are preserved. (b) RESOLVE: 'playing' -> 'resolved', backend-only. Backend writes winner, secondPlace, winnerDeltaMs, secondPlaceDeltaMs. Hook pays out winner 75% of pool, second place 20%, and 5% fee to SPIN_POOL_ID (MNY) or FEE_POOL_ID (SOL) in the match's token. Atomic. (c) CANCEL: 'waiting' -> 'cancelled', allowed only when playerCount == 1 (no other players joined). Either the creator (player-initiated) or PROJECT_VAULT_ADDRESS (cron timeout) can cancel. Hook refunds buyIn from the escrow PDA back to the creator in the original currency (MNY or SOL). Per-player refunds for cancellations with multiple joiners are out of scope. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateFlashMatches(matchId: string, data: FlashMatchesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`flashMatches/${matchId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating FlashMatches: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read matches (lobby browsing, ongoing/resolved matches).
   (Get Single Item)
 */
export async function getFlashMatches(matchId: string): Promise<FlashMatchesResponse | null> {
  try {
    const result = await get(`flashMatches/${matchId}`);
    return result as FlashMatchesResponse | null;
  } catch (error) {
    console.error(`Error getting FlashMatches: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single FlashMatches document. (
  Read Operation Details: Anyone can read matches (lobby browsing, ongoing/resolved matches).
  )
 */
export function subscribeFlashMatches(callback: (data: FlashMatchesResponse | null) => void, matchId: string): Promise<() => Promise<void>> {
  return subscribe(`flashMatches/${matchId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FlashMatchesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to FlashMatches at path '${`flashMatches/${matchId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many FlashMatches items from collection flashMatches
 
  Read Operation Details: Anyone can read matches (lobby browsing, ongoing/resolved matches).
  
 */
export async function getManyFlashMatches(filter: string = ""): Promise<FlashMatchesResponse[]> {
  try {
    const results = await get("flashMatches", { prompt: filter });
    return Array.isArray(results) ? results as FlashMatchesResponse[] : [];
  } catch (error) {
    console.error(`Error getting FlashMatches collection at path 'flashMatches': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FlashMatches collection at flashMatches
 
  Read Operation Details: Anyone can read matches (lobby browsing, ongoing/resolved matches).
  
 */
export function subscribeManyFlashMatches(callback: (data: FlashMatchesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("flashMatches", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FlashMatchesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FlashMatches collection at path '${"flashMatches"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all FlashMatches items from collection flashMatches
 
  Read Operation Details: Anyone can read matches (lobby browsing, ongoing/resolved matches).
  
 */
export async function getAllFlashMatches(filter: string = ""): Promise<FlashMatchesResponse[]> {
  try {
    const results = await get("flashMatches", { prompt: filter });
    return Array.isArray(results) ? results as FlashMatchesResponse[] : [];
  } catch (error) {
    console.error(`Error getting FlashMatches collection at path 'flashMatches': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FlashMatches collection at flashMatches
 
  Read Operation Details: Anyone can read matches (lobby browsing, ongoing/resolved matches).
  
 */
export function subscribeAllFlashMatches(callback: (data: FlashMatchesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("flashMatches", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FlashMatchesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FlashMatches collection at path '${"flashMatches"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count FlashMatches items in collection flashMatches.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countFlashMatches(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("flashMatches", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting FlashMatches at path 'flashMatches': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on FlashMatches items in collection flashMatches.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateFlashMatches(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("flashMatches", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating FlashMatches at path 'flashMatches': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getMatchEscrowAddress" query on FlashMatches.
 * Query Logic: @AccountPlugin.getAccountAddress($matchId)
 */
export async function runGetMatchEscrowAddressQueryForFlashMatches(matchId: string, ): Promise<string> {
  try {
    const result = await runQuery(`flashMatches/${matchId}`, "getMatchEscrowAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getMatchEscrowAddress" on FlashMatches: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getFeePoolAddress" query on FlashMatches.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.FEE_POOL_ID)
 */
export async function runGetFeePoolAddressQueryForFlashMatches(matchId: string, ): Promise<string> {
  try {
    const result = await runQuery(`flashMatches/${matchId}`, "getFeePoolAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getFeePoolAddress" on FlashMatches: ${formatError(error)}`);
    throw error;
  }
}

