// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: flashMatchTaps/$matchId/players/$playerAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Off-chain tap submissions for a flash match. Each player records the time (ms since match start) at which they tapped. Backend reads these to compute the player whose tap is closest to flashMomentMs and resolves the match.
 */

export interface FlashMatchTapsPlayersRequest {
  player: AddressType;
  tapTimeMs: number | TimeOperation | IncrementOperation | TokenAmount;
  submittedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface FlashMatchTapsPlayersResponse {
  player: string;
  tapTimeMs: number;
  submittedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a FlashMatchTapsPlayers operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFlashMatchTapsPlayers(matchId: string, playerAddress: string, data?: FlashMatchTapsPlayersRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `flashMatchTaps/${matchId}/players/${playerAddress}`, document: doc };
}

/**
 * Authenticated player submits exactly one tap for themselves. $playerAddress must equal @user.address. Backend filters to ensure the player is part of the flashMatches/$matchId match before counting their tap. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFlashMatchTapsPlayers(matchId: string, playerAddress: string, data?: FlashMatchTapsPlayersRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`flashMatchTaps/${matchId}/players/${playerAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting FlashMatchTapsPlayers: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read tap submissions for transparency.
   (Get Single Item)
 */
export async function getFlashMatchTapsPlayers(matchId: string, playerAddress: string): Promise<FlashMatchTapsPlayersResponse | null> {
  try {
    const result = await get(`flashMatchTaps/${matchId}/players/${playerAddress}`);
    return result as FlashMatchTapsPlayersResponse | null;
  } catch (error) {
    console.error(`Error getting FlashMatchTapsPlayers: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single FlashMatchTapsPlayers document. (
  Read Operation Details: Anyone can read tap submissions for transparency.
  )
 */
export function subscribeFlashMatchTapsPlayers(callback: (data: FlashMatchTapsPlayersResponse | null) => void, matchId: string, playerAddress: string): Promise<() => Promise<void>> {
  return subscribe(`flashMatchTaps/${matchId}/players/${playerAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FlashMatchTapsPlayersResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to FlashMatchTapsPlayers at path '${`flashMatchTaps/${matchId}/players/${playerAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many FlashMatchTapsPlayers items from collection flashMatchTaps/${matchId}/players
 
  Read Operation Details: Anyone can read tap submissions for transparency.
  
 */
export async function getManyFlashMatchTapsPlayers(matchId: string, filter: string = ""): Promise<FlashMatchTapsPlayersResponse[]> {
  try {
    const results = await get(`flashMatchTaps/${matchId}/players`, { prompt: filter });
    return Array.isArray(results) ? results as FlashMatchTapsPlayersResponse[] : [];
  } catch (error) {
    console.error(`Error getting FlashMatchTapsPlayers collection at path 'flashMatchTaps/${matchId}/players': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FlashMatchTapsPlayers collection at flashMatchTaps/${matchId}/players
 
  Read Operation Details: Anyone can read tap submissions for transparency.
  
 */
export function subscribeManyFlashMatchTapsPlayers(callback: (data: FlashMatchTapsPlayersResponse[]) => void, matchId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`flashMatchTaps/${matchId}/players`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FlashMatchTapsPlayersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FlashMatchTapsPlayers collection at path '${`flashMatchTaps/${matchId}/players`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all FlashMatchTapsPlayers items from collection flashMatchTaps/${matchId}/players
 
  Read Operation Details: Anyone can read tap submissions for transparency.
  
 */
export async function getAllFlashMatchTapsPlayers(matchId: string, filter: string = ""): Promise<FlashMatchTapsPlayersResponse[]> {
  try {
    const results = await get(`flashMatchTaps/*/players`, { prompt: filter });
    return Array.isArray(results) ? results as FlashMatchTapsPlayersResponse[] : [];
  } catch (error) {
    console.error(`Error getting FlashMatchTapsPlayers collection at path 'flashMatchTaps/${matchId}/players': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in FlashMatchTapsPlayers collection at flashMatchTaps/${matchId}/players
 
  Read Operation Details: Anyone can read tap submissions for transparency.
  
 */
export function subscribeAllFlashMatchTapsPlayers(callback: (data: FlashMatchTapsPlayersResponse[]) => void, matchId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`flashMatchTaps/*/players`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FlashMatchTapsPlayersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to FlashMatchTapsPlayers collection at path '${`flashMatchTaps/*/players`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count FlashMatchTapsPlayers items in collection flashMatchTaps/${matchId}/players.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countFlashMatchTapsPlayers(matchId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`flashMatchTaps/${matchId}/players`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting FlashMatchTapsPlayers at path 'flashMatchTaps/${matchId}/players': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on FlashMatchTapsPlayers items in collection flashMatchTaps/${matchId}/players.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateFlashMatchTapsPlayers(matchId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`flashMatchTaps/${matchId}/players`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating FlashMatchTapsPlayers at path 'flashMatchTaps/${matchId}/players': ${formatError(error)}`);
    return { value: 0 };
  }
}

