// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: gameSubmissions/$gameId/players/$playerAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Player tap-count submissions for a game. Each player submits once after the 10-second tap phase. Backend reads these to determine winner/second place.
 */

export interface GameSubmissionsPlayersRequest {
  gameId: string;
  player: AddressType;
  tapCount: number | IncrementOperation | TokenAmount;
  submittedAt: number | IncrementOperation | TokenAmount;
}

export interface GameSubmissionsPlayersResponse {
  gameId: string;
  player: string;
  tapCount: number;
  submittedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a GameSubmissionsPlayers operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildGameSubmissionsPlayers(gameId: string, playerAddress: string, data?: GameSubmissionsPlayersRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `gameSubmissions/${gameId}/players/${playerAddress}`, document: doc };
}

/**
 * Players can only submit for themselves ($playerAddress must equal @user.address). Backend filters to ensure player is part of the referenced game when computing the winner. One-shot submission. Path uses subcollection 'players' between $gameId and $playerAddress. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setGameSubmissionsPlayers(gameId: string, playerAddress: string, data?: GameSubmissionsPlayersRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`gameSubmissions/${gameId}/players/${playerAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting GameSubmissionsPlayers: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read submissions (publicly verifiable scores).
   (Get Single Item)
 */
export async function getGameSubmissionsPlayers(gameId: string, playerAddress: string): Promise<GameSubmissionsPlayersResponse | null> {
  try {
    const result = await get(`gameSubmissions/${gameId}/players/${playerAddress}`);
    return result as GameSubmissionsPlayersResponse | null;
  } catch (error) {
    console.error(`Error getting GameSubmissionsPlayers: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single GameSubmissionsPlayers document. (
  Read Operation Details: Anyone can read submissions (publicly verifiable scores).
  )
 */
export function subscribeGameSubmissionsPlayers(callback: (data: GameSubmissionsPlayersResponse | null) => void, gameId: string, playerAddress: string): Promise<() => Promise<void>> {
  return subscribe(`gameSubmissions/${gameId}/players/${playerAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as GameSubmissionsPlayersResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to GameSubmissionsPlayers at path '${`gameSubmissions/${gameId}/players/${playerAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many GameSubmissionsPlayers items from collection gameSubmissions/${gameId}/players
 
  Read Operation Details: Anyone can read submissions (publicly verifiable scores).
  
 */
export async function getManyGameSubmissionsPlayers(gameId: string, filter: string = ""): Promise<GameSubmissionsPlayersResponse[]> {
  try {
    const results = await get(`gameSubmissions/${gameId}/players`, { prompt: filter });
    return Array.isArray(results) ? results as GameSubmissionsPlayersResponse[] : [];
  } catch (error) {
    console.error(`Error getting GameSubmissionsPlayers collection at path 'gameSubmissions/${gameId}/players': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in GameSubmissionsPlayers collection at gameSubmissions/${gameId}/players
 
  Read Operation Details: Anyone can read submissions (publicly verifiable scores).
  
 */
export function subscribeManyGameSubmissionsPlayers(callback: (data: GameSubmissionsPlayersResponse[]) => void, gameId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`gameSubmissions/${gameId}/players`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as GameSubmissionsPlayersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to GameSubmissionsPlayers collection at path '${`gameSubmissions/${gameId}/players`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all GameSubmissionsPlayers items from collection gameSubmissions/${gameId}/players
 
  Read Operation Details: Anyone can read submissions (publicly verifiable scores).
  
 */
export async function getAllGameSubmissionsPlayers(gameId: string, filter: string = ""): Promise<GameSubmissionsPlayersResponse[]> {
  try {
    const results = await get(`gameSubmissions/*/players`, { prompt: filter });
    return Array.isArray(results) ? results as GameSubmissionsPlayersResponse[] : [];
  } catch (error) {
    console.error(`Error getting GameSubmissionsPlayers collection at path 'gameSubmissions/${gameId}/players': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in GameSubmissionsPlayers collection at gameSubmissions/${gameId}/players
 
  Read Operation Details: Anyone can read submissions (publicly verifiable scores).
  
 */
export function subscribeAllGameSubmissionsPlayers(callback: (data: GameSubmissionsPlayersResponse[]) => void, gameId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`gameSubmissions/*/players`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as GameSubmissionsPlayersResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to GameSubmissionsPlayers collection at path '${`gameSubmissions/*/players`}': ${formatError(error)}`);
    }
  });
}

/**
 * Count GameSubmissionsPlayers items in collection gameSubmissions/${gameId}/players.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countGameSubmissionsPlayers(gameId: string, filter: string = ""): Promise<AggregateResult> {
  try {
    return await count(`gameSubmissions/${gameId}/players`, { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting GameSubmissionsPlayers at path 'gameSubmissions/${gameId}/players': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on GameSubmissionsPlayers items in collection gameSubmissions/${gameId}/players.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateGameSubmissionsPlayers(gameId: string, operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate(`gameSubmissions/${gameId}/players`, operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating GameSubmissionsPlayers at path 'gameSubmissions/${gameId}/players': ${formatError(error)}`);
    return { value: 0 };
  }
}

