// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: games/$gameId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * 4-player tap-race gambling game with per-game escrow PDA. Players pay tiered buy-in (Casual 0.01, Standard 0.1, High Stakes 0.5 SOL) to join. Winner gets 75% of pool, second gets 20%, platform takes 5% fee. If no joiners have entered (playerCount == 1), the match can be cancelled by either the creator or PROJECT_VAULT_ADDRESS (cron timeout), and the creator's buy-in is refunded from the escrow PDA.
 */

export interface GamesRequest {
  creator: AddressType;
  player2?: AddressType;
  player3?: AddressType;
  player4?: AddressType;
  playerCount: number | IncrementOperation | TokenAmount;
  state: string;
  createdAt: number | IncrementOperation | TokenAmount;
  startedAt: number | IncrementOperation | TokenAmount;
  winner?: AddressType;
  secondPlace?: AddressType;
  winnerScore: number | IncrementOperation | TokenAmount;
  secondPlaceScore: number | IncrementOperation | TokenAmount;
  gameType?: string;
  buyIn: number | TimeOperation | IncrementOperation | TokenAmount;
  buyInCurrency: string;
}

export interface GamesResponse {
  creator: string;
  player2?: string;
  player3?: string;
  player4?: string;
  playerCount: number;
  state: string;
  createdAt: number;
  startedAt: number;
  winner?: string;
  secondPlace?: string;
  winnerScore: number;
  secondPlaceScore: number;
  gameType?: string;
  buyIn: number;
  buyInCurrency: string;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a Games operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildGames(gameId: string, data: GamesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `games/${gameId}`, document: doc };
}

/**
 * Any authenticated non-vault user can create a game. Creator becomes player 1, pays buyIn into a per-game escrow PDA created via @AccountPlugin.createAccount($gameId). Must specify buyInCurrency ('SOL' or 'MNY'). For SOL, buyIn must be one of: 10000000 (0.01 SOL Casual), 100000000 (0.1 SOL Standard), or 500000000 (0.5 SOL High Stakes). For MNY, buyIn must be greater than 0 in MNY base units. Initial fields enforced: state='waiting', playerCount=1, winnerScore=0, secondPlaceScore=0. Optional gameType field can be set on creation and is immutable after creation. Hook ensures SPIN_POOL_ID PDA exists for MNY games and transfers buyIn from creator to escrow in the correct token. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setGames(gameId: string, data: GamesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`games/${gameId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Games: ${formatError(error)}`);
    return false;
  }
}

export type GamesRequestUpdate = Partial<GamesRequest>;

/**
 * Build a Games update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateGames(gameId: string, data: GamesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `games/${gameId}`, document: doc };
}

/**
 * Three allowed transitions: (a) JOIN — non-vault user (not already in game) joins a waiting game by occupying the next free player slot (player2/3/4), playerCount increments by 1, state flips to 'playing' on the 4th joiner, and buyIn is transferred to the escrow PDA in the game's token (MNY or SOL). gameType, buyIn, and buyInCurrency are preserved unchanged. (b) RESOLVE — only PROJECT_VAULT_ADDRESS can transition state from 'playing' to 'resolved' setting winner/secondPlace/scores; escrow pays winner 75% of pool, second 20%, and 5% platform fee to SPIN_POOL_ID (MNY) or ADMIN_ADDRESS (SOL) in the game's token. gameType, buyIn, and buyInCurrency are preserved unchanged. (c) CANCEL — allowed only when state='waiting' and playerCount == 1 (no joiners). Either the creator (player-initiated) or PROJECT_VAULT_ADDRESS (cron timeout) sets state='cancelled'. All immutable fields (creator, player2, player3, player4, playerCount, gameType, buyIn, buyInCurrency, createdAt, startedAt) are preserved; winner/secondPlace stay null and winnerScore/secondPlaceScore stay 0. Hook refunds buyIn from the escrow PDA back to the creator in the original currency (MNY or SOL). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateGames(gameId: string, data: GamesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`games/${gameId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Games: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can view games to find waiting games to join or watch ongoing/resolved games. Includes optional gameType field for multi-game architecture.
   (Get Single Item)
 */
export async function getGames(gameId: string): Promise<GamesResponse | null> {
  try {
    const result = await get(`games/${gameId}`);
    return result as GamesResponse | null;
  } catch (error) {
    console.error(`Error getting Games: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Games document. (
  Read Operation Details: Anyone can view games to find waiting games to join or watch ongoing/resolved games. Includes optional gameType field for multi-game architecture.
  )
 */
export function subscribeGames(callback: (data: GamesResponse | null) => void, gameId: string): Promise<() => Promise<void>> {
  return subscribe(`games/${gameId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as GamesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Games at path '${`games/${gameId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Games items from collection games
 
  Read Operation Details: Anyone can view games to find waiting games to join or watch ongoing/resolved games. Includes optional gameType field for multi-game architecture.
  
 */
export async function getManyGames(filter: string = ""): Promise<GamesResponse[]> {
  try {
    const results = await get("games", { prompt: filter });
    return Array.isArray(results) ? results as GamesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Games collection at path 'games': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Games collection at games
 
  Read Operation Details: Anyone can view games to find waiting games to join or watch ongoing/resolved games. Includes optional gameType field for multi-game architecture.
  
 */
export function subscribeManyGames(callback: (data: GamesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("games", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as GamesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Games collection at path '${"games"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Games items from collection games
 
  Read Operation Details: Anyone can view games to find waiting games to join or watch ongoing/resolved games. Includes optional gameType field for multi-game architecture.
  
 */
export async function getAllGames(filter: string = ""): Promise<GamesResponse[]> {
  try {
    const results = await get("games", { prompt: filter });
    return Array.isArray(results) ? results as GamesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Games collection at path 'games': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Games collection at games
 
  Read Operation Details: Anyone can view games to find waiting games to join or watch ongoing/resolved games. Includes optional gameType field for multi-game architecture.
  
 */
export function subscribeAllGames(callback: (data: GamesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("games", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as GamesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Games collection at path '${"games"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count Games items in collection games.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countGames(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("games", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting Games at path 'games': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on Games items in collection games.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateGames(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("games", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating Games at path 'games': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getEscrowAddress" query on Games.
 * Query Logic: @AccountPlugin.getAccountAddress($gameId)
 */
export async function runGetEscrowAddressQueryForGames(gameId: string, ): Promise<string> {
  try {
    const result = await runQuery(`games/${gameId}`, "getEscrowAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getEscrowAddress" on Games: ${formatError(error)}`);
    throw error;
  }
}

