// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.399Z
// Collection: mnyStakes/$stakerAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * MNY token staking positions. One document per staker (document ID = staker wallet address). Stakers receive pro-rata share of hourly SOL fee pool distributions based on amountStaked. Stake increases/decreases happen via update; the delta between @newData.amountStaked and @data.amountStaked drives token transfers between the user wallet and the MNY_STAKE_POOL_ID PDA.
 */

export interface MnyStakesRequest {
  stakerAddress: AddressType;
  amountStaked: number | TimeOperation | IncrementOperation | TokenAmount;
  stakedAt: number | TimeOperation | IncrementOperation | TokenAmount;
  unstakedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface MnyStakesResponse {
  stakerAddress: string;
  amountStaked: number;
  stakedAt: number;
  unstakedAt: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a MnyStakes operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildMnyStakes(stakerAddress: string, data: MnyStakesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `mnyStakes/${stakerAddress}`, document: doc };
}

/**
 * Authenticated user creating their own stake doc. Document ID must equal @user.address. Initial amountStaked must be > 0. Hook ensures the MNY_STAKE_POOL_ID PDA exists, then transfers @newData.amountStaked MNY base units from the user to the PDA. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setMnyStakes(stakerAddress: string, data: MnyStakesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`mnyStakes/${stakerAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting MnyStakes: ${formatError(error)}`);
    return false;
  }
}

export type MnyStakesRequestUpdate = Partial<MnyStakesRequest>;

/**
 * Build a MnyStakes update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateMnyStakes(stakerAddress: string, data: MnyStakesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `mnyStakes/${stakerAddress}`, document: doc };
}

/**
 * Staker (or PROJECT_VAULT_ADDRESS for admin/maintenance) updates amountStaked. stakerAddress is immutable post-create. Hook idempotently handles the delta: increases transfer MNY from user to MNY_STAKE_POOL_ID, decreases transfer MNY from MNY_STAKE_POOL_ID back to user, equal values are a no-op. Frontend must update stakedAt on stake increases and unstakedAt on stake decreases. Setting amountStaked to 0 is allowed and effectively unstakes everything. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateMnyStakes(stakerAddress: string, data: MnyStakesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`mnyStakes/${stakerAddress}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating MnyStakes: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read stakes. Public so backend snapshots and frontends can display staker leaderboards and totals.
   (Get Single Item)
 */
export async function getMnyStakes(stakerAddress: string): Promise<MnyStakesResponse | null> {
  try {
    const result = await get(`mnyStakes/${stakerAddress}`);
    return result as MnyStakesResponse | null;
  } catch (error) {
    console.error(`Error getting MnyStakes: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single MnyStakes document. (
  Read Operation Details: Anyone can read stakes. Public so backend snapshots and frontends can display staker leaderboards and totals.
  )
 */
export function subscribeMnyStakes(callback: (data: MnyStakesResponse | null) => void, stakerAddress: string): Promise<() => Promise<void>> {
  return subscribe(`mnyStakes/${stakerAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as MnyStakesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to MnyStakes at path '${`mnyStakes/${stakerAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many MnyStakes items from collection mnyStakes
 
  Read Operation Details: Anyone can read stakes. Public so backend snapshots and frontends can display staker leaderboards and totals.
  
 */
export async function getManyMnyStakes(filter: string = ""): Promise<MnyStakesResponse[]> {
  try {
    const results = await get("mnyStakes", { prompt: filter });
    return Array.isArray(results) ? results as MnyStakesResponse[] : [];
  } catch (error) {
    console.error(`Error getting MnyStakes collection at path 'mnyStakes': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MnyStakes collection at mnyStakes
 
  Read Operation Details: Anyone can read stakes. Public so backend snapshots and frontends can display staker leaderboards and totals.
  
 */
export function subscribeManyMnyStakes(callback: (data: MnyStakesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("mnyStakes", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MnyStakesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MnyStakes collection at path '${"mnyStakes"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all MnyStakes items from collection mnyStakes
 
  Read Operation Details: Anyone can read stakes. Public so backend snapshots and frontends can display staker leaderboards and totals.
  
 */
export async function getAllMnyStakes(filter: string = ""): Promise<MnyStakesResponse[]> {
  try {
    const results = await get("mnyStakes", { prompt: filter });
    return Array.isArray(results) ? results as MnyStakesResponse[] : [];
  } catch (error) {
    console.error(`Error getting MnyStakes collection at path 'mnyStakes': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in MnyStakes collection at mnyStakes
 
  Read Operation Details: Anyone can read stakes. Public so backend snapshots and frontends can display staker leaderboards and totals.
  
 */
export function subscribeAllMnyStakes(callback: (data: MnyStakesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("mnyStakes", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MnyStakesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to MnyStakes collection at path '${"mnyStakes"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count MnyStakes items in collection mnyStakes.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countMnyStakes(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("mnyStakes", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting MnyStakes at path 'mnyStakes': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on MnyStakes items in collection mnyStakes.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateMnyStakes(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("mnyStakes", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating MnyStakes at path 'mnyStakes': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getStakePoolAddress" query on MnyStakes.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.MNY_STAKE_POOL_ID)
 */
export async function runGetStakePoolAddressQueryForMnyStakes(stakerAddress: string, ): Promise<string> {
  try {
    const result = await runQuery(`mnyStakes/${stakerAddress}`, "getStakePoolAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getStakePoolAddress" on MnyStakes: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getMnyMintAddress" query on MnyStakes.
 * Query Logic: @TokenPlugin.getTokenMintAddress(@constants.TPR_TOKEN_ID, @constants.TPR_NAME, @constants.TPR_SYMBOL)
 */
export async function runGetMnyMintAddressQueryForMnyStakes(stakerAddress: string, ): Promise<string> {
  try {
    const result = await runQuery(`mnyStakes/${stakerAddress}`, "getMnyMintAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getMnyMintAddress" on MnyStakes: ${formatError(error)}`);
    throw error;
  }
}

