// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.399Z
// Collection: seedSpinPool/$seedId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Admin-only seeding records that move MNY tokens from the TPR_TREASURY_ID PDA into the SPIN_POOL_ID PDA to bootstrap or top up the daily spin prize pool. Mirrors the MNY fee pattern used by flashMatches/rpsMatches (which transfer MNY into SPIN_POOL_ID via @TokenPlugin.transfer using @TokenPlugin.getTokenMintAddress(TPR_TOKEN_ID, TPR_NAME, TPR_SYMBOL) as the mint). Onchain create hook ensures SPIN_POOL_ID exists, transfers MNY treasury -> spin pool, then bumps dailySpinPool/main.balance so the UI sees the new pool size. Append-only / immutable.
 */

export interface SeedSpinPoolRequest {
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  createdBy: AddressType;
}

export interface SeedSpinPoolResponse {
  amount: number;
  createdAt: number;
  createdBy: string;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SeedSpinPool operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSeedSpinPool(seedId: string, data?: SeedSpinPoolRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `seedSpinPool/${seedId}`, document: doc };
}

/**
 * ADMIN_ADDRESS or PROJECT_VAULT_ADDRESS only (latter allows backend/MCP tools that sign as the project vault to seed the pool). createdBy must equal @user.address and amount must be > 0 (raw MNY base units). Hook ensures TPR_TREASURY_ID and SPIN_POOL_ID PDAs exist, transfers `amount` MNY from TPR_TREASURY_ID to SPIN_POOL_ID using @TokenPlugin.transfer (mint = @TokenPlugin.getTokenMintAddress(TPR_TOKEN_ID, TPR_NAME, TPR_SYMBOL)), then bumps dailySpinPool/main.balance by `amount` if that singleton already exists. If dailySpinPool/main has not yet been initialized by the backend, the onchain MNY transfer still succeeds (treasury -> spin pool); the balance field will be reconciled the next time the spin backend writes to dailySpinPool. Frontend should pass createdAt as Unix seconds and the document ID can be any non-pubkey string (e.g. `seed_{timestamp}_{randomSuffix}`). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSeedSpinPool(seedId: string, data?: SeedSpinPoolRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`seedSpinPool/${seedId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SeedSpinPool: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read seeding records (admin audit trail of treasury -> spin pool top-ups).
   (Get Single Item)
 */
export async function getSeedSpinPool(seedId: string): Promise<SeedSpinPoolResponse | null> {
  try {
    const result = await get(`seedSpinPool/${seedId}`);
    return result as SeedSpinPoolResponse | null;
  } catch (error) {
    console.error(`Error getting SeedSpinPool: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SeedSpinPool document. (
  Read Operation Details: Anyone can read seeding records (admin audit trail of treasury -> spin pool top-ups).
  )
 */
export function subscribeSeedSpinPool(callback: (data: SeedSpinPoolResponse | null) => void, seedId: string): Promise<() => Promise<void>> {
  return subscribe(`seedSpinPool/${seedId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SeedSpinPoolResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SeedSpinPool at path '${`seedSpinPool/${seedId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SeedSpinPool items from collection seedSpinPool
 
  Read Operation Details: Anyone can read seeding records (admin audit trail of treasury -> spin pool top-ups).
  
 */
export async function getManySeedSpinPool(filter: string = ""): Promise<SeedSpinPoolResponse[]> {
  try {
    const results = await get("seedSpinPool", { prompt: filter });
    return Array.isArray(results) ? results as SeedSpinPoolResponse[] : [];
  } catch (error) {
    console.error(`Error getting SeedSpinPool collection at path 'seedSpinPool': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SeedSpinPool collection at seedSpinPool
 
  Read Operation Details: Anyone can read seeding records (admin audit trail of treasury -> spin pool top-ups).
  
 */
export function subscribeManySeedSpinPool(callback: (data: SeedSpinPoolResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("seedSpinPool", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SeedSpinPoolResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SeedSpinPool collection at path '${"seedSpinPool"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SeedSpinPool items from collection seedSpinPool
 
  Read Operation Details: Anyone can read seeding records (admin audit trail of treasury -> spin pool top-ups).
  
 */
export async function getAllSeedSpinPool(filter: string = ""): Promise<SeedSpinPoolResponse[]> {
  try {
    const results = await get("seedSpinPool", { prompt: filter });
    return Array.isArray(results) ? results as SeedSpinPoolResponse[] : [];
  } catch (error) {
    console.error(`Error getting SeedSpinPool collection at path 'seedSpinPool': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SeedSpinPool collection at seedSpinPool
 
  Read Operation Details: Anyone can read seeding records (admin audit trail of treasury -> spin pool top-ups).
  
 */
export function subscribeAllSeedSpinPool(callback: (data: SeedSpinPoolResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("seedSpinPool", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SeedSpinPoolResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SeedSpinPool collection at path '${"seedSpinPool"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SeedSpinPool items in collection seedSpinPool.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSeedSpinPool(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("seedSpinPool", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SeedSpinPool at path 'seedSpinPool': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SeedSpinPool items in collection seedSpinPool.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSeedSpinPool(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("seedSpinPool", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SeedSpinPool at path 'seedSpinPool': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getTreasuryAddress" query on SeedSpinPool.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.TPR_TREASURY_ID)
 */
export async function runGetTreasuryAddressQueryForSeedSpinPool(seedId: string, ): Promise<string> {
  try {
    const result = await runQuery(`seedSpinPool/${seedId}`, "getTreasuryAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getTreasuryAddress" on SeedSpinPool: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getSpinPoolAddress" query on SeedSpinPool.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.SPIN_POOL_ID)
 */
export async function runGetSpinPoolAddressQueryForSeedSpinPool(seedId: string, ): Promise<string> {
  try {
    const result = await runQuery(`seedSpinPool/${seedId}`, "getSpinPoolAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getSpinPoolAddress" on SeedSpinPool: ${formatError(error)}`);
    throw error;
  }
}

