// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.399Z
// Collection: spinPayouts/$payoutId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * On-chain payout trigger for daily spin prizes. When the backend creates a record, MNY tokens are atomically transferred from the SPIN_POOL_ID PDA to the winning user's wallet.
 */

export interface SpinPayoutsRequest {
  recipient: AddressType;
  amount: number | TimeOperation | IncrementOperation | TokenAmount;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface SpinPayoutsResponse {
  recipient: string;
  amount: number;
  ts: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a SpinPayouts operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSpinPayouts(payoutId: string, data?: SpinPayoutsRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `spinPayouts/${payoutId}`, document: doc };
}

/**
 * Backend-only (PROJECT_VAULT_ADDRESS). Created by /api/daily-spin when a user wins a non-zero prize. Hook transfers MNY from SPIN_POOL_ID PDA to the recipient atomically. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSpinPayouts(payoutId: string, data?: SpinPayoutsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`spinPayouts/${payoutId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting SpinPayouts: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read spin payout records.
   (Get Single Item)
 */
export async function getSpinPayouts(payoutId: string): Promise<SpinPayoutsResponse | null> {
  try {
    const result = await get(`spinPayouts/${payoutId}`);
    return result as SpinPayoutsResponse | null;
  } catch (error) {
    console.error(`Error getting SpinPayouts: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single SpinPayouts document. (
  Read Operation Details: Anyone can read spin payout records.
  )
 */
export function subscribeSpinPayouts(callback: (data: SpinPayoutsResponse | null) => void, payoutId: string): Promise<() => Promise<void>> {
  return subscribe(`spinPayouts/${payoutId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SpinPayoutsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to SpinPayouts at path '${`spinPayouts/${payoutId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many SpinPayouts items from collection spinPayouts
 
  Read Operation Details: Anyone can read spin payout records.
  
 */
export async function getManySpinPayouts(filter: string = ""): Promise<SpinPayoutsResponse[]> {
  try {
    const results = await get("spinPayouts", { prompt: filter });
    return Array.isArray(results) ? results as SpinPayoutsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SpinPayouts collection at path 'spinPayouts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SpinPayouts collection at spinPayouts
 
  Read Operation Details: Anyone can read spin payout records.
  
 */
export function subscribeManySpinPayouts(callback: (data: SpinPayoutsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("spinPayouts", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SpinPayoutsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SpinPayouts collection at path '${"spinPayouts"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all SpinPayouts items from collection spinPayouts
 
  Read Operation Details: Anyone can read spin payout records.
  
 */
export async function getAllSpinPayouts(filter: string = ""): Promise<SpinPayoutsResponse[]> {
  try {
    const results = await get("spinPayouts", { prompt: filter });
    return Array.isArray(results) ? results as SpinPayoutsResponse[] : [];
  } catch (error) {
    console.error(`Error getting SpinPayouts collection at path 'spinPayouts': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in SpinPayouts collection at spinPayouts
 
  Read Operation Details: Anyone can read spin payout records.
  
 */
export function subscribeAllSpinPayouts(callback: (data: SpinPayoutsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("spinPayouts", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SpinPayoutsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to SpinPayouts collection at path '${"spinPayouts"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count SpinPayouts items in collection spinPayouts.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countSpinPayouts(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("spinPayouts", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting SpinPayouts at path 'spinPayouts': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on SpinPayouts items in collection spinPayouts.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateSpinPayouts(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("spinPayouts", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating SpinPayouts at path 'spinPayouts': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getSpinPoolAddress" query on SpinPayouts.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.SPIN_POOL_ID)
 */
export async function runGetSpinPoolAddressQueryForSpinPayouts(payoutId: string, ): Promise<string> {
  try {
    const result = await runQuery(`spinPayouts/${payoutId}`, "getSpinPoolAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getSpinPoolAddress" on SpinPayouts: ${formatError(error)}`);
    throw error;
  }
}

