// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: tokenUnlockStats/$id
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Singleton tracker for cumulative PPP token unlocks. Holds totalUnlocked so anyone can query how much has been released from treasury. Created lazily by the first unlock via @DocumentPlugin.updateField. The single document ID is 'main'.
 */

export interface TokenUnlockStatsRequest {
  totalUnlocked: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TokenUnlockStatsResponse {
  totalUnlocked: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * 
  Read Operation Details: Anyone can read the running total to see cumulative unlocked supply.
   (Get Single Item)
 */
export async function getTokenUnlockStats(id: string): Promise<TokenUnlockStatsResponse | null> {
  try {
    const result = await get(`tokenUnlockStats/${id}`);
    return result as TokenUnlockStatsResponse | null;
  } catch (error) {
    console.error(`Error getting TokenUnlockStats: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single TokenUnlockStats document. (
  Read Operation Details: Anyone can read the running total to see cumulative unlocked supply.
  )
 */
export function subscribeTokenUnlockStats(callback: (data: TokenUnlockStatsResponse | null) => void, id: string): Promise<() => Promise<void>> {
  return subscribe(`tokenUnlockStats/${id}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TokenUnlockStatsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to TokenUnlockStats at path '${`tokenUnlockStats/${id}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many TokenUnlockStats items from collection tokenUnlockStats
 
  Read Operation Details: Anyone can read the running total to see cumulative unlocked supply.
  
 */
export async function getManyTokenUnlockStats(filter: string = ""): Promise<TokenUnlockStatsResponse[]> {
  try {
    const results = await get("tokenUnlockStats", { prompt: filter });
    return Array.isArray(results) ? results as TokenUnlockStatsResponse[] : [];
  } catch (error) {
    console.error(`Error getting TokenUnlockStats collection at path 'tokenUnlockStats': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TokenUnlockStats collection at tokenUnlockStats
 
  Read Operation Details: Anyone can read the running total to see cumulative unlocked supply.
  
 */
export function subscribeManyTokenUnlockStats(callback: (data: TokenUnlockStatsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tokenUnlockStats", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TokenUnlockStatsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TokenUnlockStats collection at path '${"tokenUnlockStats"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all TokenUnlockStats items from collection tokenUnlockStats
 
  Read Operation Details: Anyone can read the running total to see cumulative unlocked supply.
  
 */
export async function getAllTokenUnlockStats(filter: string = ""): Promise<TokenUnlockStatsResponse[]> {
  try {
    const results = await get("tokenUnlockStats", { prompt: filter });
    return Array.isArray(results) ? results as TokenUnlockStatsResponse[] : [];
  } catch (error) {
    console.error(`Error getting TokenUnlockStats collection at path 'tokenUnlockStats': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TokenUnlockStats collection at tokenUnlockStats
 
  Read Operation Details: Anyone can read the running total to see cumulative unlocked supply.
  
 */
export function subscribeAllTokenUnlockStats(callback: (data: TokenUnlockStatsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tokenUnlockStats", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TokenUnlockStatsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TokenUnlockStats collection at path '${"tokenUnlockStats"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count TokenUnlockStats items in collection tokenUnlockStats.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countTokenUnlockStats(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("tokenUnlockStats", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting TokenUnlockStats at path 'tokenUnlockStats': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on TokenUnlockStats items in collection tokenUnlockStats.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateTokenUnlockStats(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("tokenUnlockStats", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating TokenUnlockStats at path 'tokenUnlockStats': ${formatError(error)}`);
    return { value: 0 };
  }
}

