// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: tprBuyerStats/$buyerAddress
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Singleton tracker per buyer for the TPR primary sale. Holds cumulative totalPurchasedBaseUnits to enforce the 5,000 MNY (= 5,000 * 10^6 base units) per-wallet cap atomically. Created lazily by the first primary-sale purchase via @DocumentPlugin.updateField. Document ID is the buyer wallet address.
 */

export interface TprBuyerStatsRequest {
  totalPurchasedBaseUnits: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TprBuyerStatsResponse {
  totalPurchasedBaseUnits: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * 
  Read Operation Details: Anyone can read a buyer's cumulative primary-sale purchase total. Used to compute remaining per-wallet allowance.
   (Get Single Item)
 */
export async function getTprBuyerStats(buyerAddress: string): Promise<TprBuyerStatsResponse | null> {
  try {
    const result = await get(`tprBuyerStats/${buyerAddress}`);
    return result as TprBuyerStatsResponse | null;
  } catch (error) {
    console.error(`Error getting TprBuyerStats: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single TprBuyerStats document. (
  Read Operation Details: Anyone can read a buyer's cumulative primary-sale purchase total. Used to compute remaining per-wallet allowance.
  )
 */
export function subscribeTprBuyerStats(callback: (data: TprBuyerStatsResponse | null) => void, buyerAddress: string): Promise<() => Promise<void>> {
  return subscribe(`tprBuyerStats/${buyerAddress}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TprBuyerStatsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to TprBuyerStats at path '${`tprBuyerStats/${buyerAddress}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many TprBuyerStats items from collection tprBuyerStats
 
  Read Operation Details: Anyone can read a buyer's cumulative primary-sale purchase total. Used to compute remaining per-wallet allowance.
  
 */
export async function getManyTprBuyerStats(filter: string = ""): Promise<TprBuyerStatsResponse[]> {
  try {
    const results = await get("tprBuyerStats", { prompt: filter });
    return Array.isArray(results) ? results as TprBuyerStatsResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprBuyerStats collection at path 'tprBuyerStats': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprBuyerStats collection at tprBuyerStats
 
  Read Operation Details: Anyone can read a buyer's cumulative primary-sale purchase total. Used to compute remaining per-wallet allowance.
  
 */
export function subscribeManyTprBuyerStats(callback: (data: TprBuyerStatsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprBuyerStats", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprBuyerStatsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprBuyerStats collection at path '${"tprBuyerStats"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all TprBuyerStats items from collection tprBuyerStats
 
  Read Operation Details: Anyone can read a buyer's cumulative primary-sale purchase total. Used to compute remaining per-wallet allowance.
  
 */
export async function getAllTprBuyerStats(filter: string = ""): Promise<TprBuyerStatsResponse[]> {
  try {
    const results = await get("tprBuyerStats", { prompt: filter });
    return Array.isArray(results) ? results as TprBuyerStatsResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprBuyerStats collection at path 'tprBuyerStats': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprBuyerStats collection at tprBuyerStats
 
  Read Operation Details: Anyone can read a buyer's cumulative primary-sale purchase total. Used to compute remaining per-wallet allowance.
  
 */
export function subscribeAllTprBuyerStats(callback: (data: TprBuyerStatsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprBuyerStats", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprBuyerStatsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprBuyerStats collection at path '${"tprBuyerStats"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count TprBuyerStats items in collection tprBuyerStats.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countTprBuyerStats(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("tprBuyerStats", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting TprBuyerStats at path 'tprBuyerStats': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on TprBuyerStats items in collection tprBuyerStats.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateTprBuyerStats(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("tprBuyerStats", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating TprBuyerStats at path 'tprBuyerStats': ${formatError(error)}`);
    return { value: 0 };
  }
}

