// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: tprListings/$listingId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Secondary-market listings: MNY holders escrow tokens into a per-listing PDA and set a SOL price. Anyone can buy at the listed price. Seller can cancel and reclaim tokens.
 */

export interface TprListingsRequest {
  seller: AddressType;
  pricePerWholeTokenLamports: number | TimeOperation | IncrementOperation | TokenAmount;
  active: boolean;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
  tprAmountBaseUnits: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TprListingsResponse {
  seller: string;
  pricePerWholeTokenLamports: number;
  active: boolean;
  ts: number;
  tprAmountBaseUnits: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a TprListings operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildTprListings(listingId: string, data: TprListingsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `tprListings/${listingId}`, document: doc };
}

/**
 * Authenticated seller creates a listing. Seller must equal @user.address. Hook creates a per-listing PDA and transfers the listed MNY amount from the seller into that PDA. The listing starts active=true. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setTprListings(listingId: string, data: TprListingsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`tprListings/${listingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting TprListings: ${formatError(error)}`);
    return false;
  }
}

export type TprListingsRequestUpdate = Partial<TprListingsRequest>;

/**
 * Build a TprListings update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateTprListings(listingId: string, data: TprListingsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `tprListings/${listingId}`, document: doc };
}

/**
 * Only the seller can update, and only to cancel (active true -> false). All other fields must remain unchanged. Hook returns the escrowed MNY tokens from the listing PDA back to the seller. Buying happens via the tprPurchases collection (which sets active=false through that flow's hook). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateTprListings(listingId: string, data: TprListingsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`tprListings/${listingId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating TprListings: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can browse open and closed listings.
   (Get Single Item)
 */
export async function getTprListings(listingId: string): Promise<TprListingsResponse | null> {
  try {
    const result = await get(`tprListings/${listingId}`);
    return result as TprListingsResponse | null;
  } catch (error) {
    console.error(`Error getting TprListings: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single TprListings document. (
  Read Operation Details: Anyone can browse open and closed listings.
  )
 */
export function subscribeTprListings(callback: (data: TprListingsResponse | null) => void, listingId: string): Promise<() => Promise<void>> {
  return subscribe(`tprListings/${listingId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TprListingsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to TprListings at path '${`tprListings/${listingId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many TprListings items from collection tprListings
 
  Read Operation Details: Anyone can browse open and closed listings.
  
 */
export async function getManyTprListings(filter: string = ""): Promise<TprListingsResponse[]> {
  try {
    const results = await get("tprListings", { prompt: filter });
    return Array.isArray(results) ? results as TprListingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprListings collection at path 'tprListings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprListings collection at tprListings
 
  Read Operation Details: Anyone can browse open and closed listings.
  
 */
export function subscribeManyTprListings(callback: (data: TprListingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprListings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprListingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprListings collection at path '${"tprListings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all TprListings items from collection tprListings
 
  Read Operation Details: Anyone can browse open and closed listings.
  
 */
export async function getAllTprListings(filter: string = ""): Promise<TprListingsResponse[]> {
  try {
    const results = await get("tprListings", { prompt: filter });
    return Array.isArray(results) ? results as TprListingsResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprListings collection at path 'tprListings': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprListings collection at tprListings
 
  Read Operation Details: Anyone can browse open and closed listings.
  
 */
export function subscribeAllTprListings(callback: (data: TprListingsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprListings", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprListingsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprListings collection at path '${"tprListings"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count TprListings items in collection tprListings.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countTprListings(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("tprListings", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting TprListings at path 'tprListings': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on TprListings items in collection tprListings.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateTprListings(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("tprListings", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating TprListings at path 'tprListings': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getListingEscrowAddress" query on TprListings.
 * Query Logic: @AccountPlugin.getAccountAddress($listingId)
 */
export async function runGetListingEscrowAddressQueryForTprListings(listingId: string, ): Promise<string> {
  try {
    const result = await runQuery(`tprListings/${listingId}`, "getListingEscrowAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getListingEscrowAddress" on TprListings: ${formatError(error)}`);
    throw error;
  }
}

