// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: tprPrimarySales/$saleId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Primary-sale purchase records for the MNY token. Buyer transfers SOL to ADMIN (dev earnings) and receives MNY from the treasury PDA. Two caps enforced: (1) global tranche cap via tprPrimarySaleStats/main, (2) per-wallet cap of 5,000 MNY via tprBuyerStats/$buyerAddress. Sale price is configurable per-tranche via tprSalePrice/main with fallback to TPR_PRIMARY_SALE_PRICE_LAMPORTS constant. isPassthrough=true so no permanent onchain row is stored - the off-chain copy still records the sale.
 */

export interface TprPrimarySalesRequest {
  buyer: AddressType;
  solAmountLamports: number | TimeOperation | IncrementOperation | TokenAmount;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
  tprAmountBaseUnits: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TprPrimarySalesResponse {
  buyer: string;
  solAmountLamports: number;
  ts: number;
  tprAmountBaseUnits: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a TprPrimarySales operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildTprPrimarySales(saleId: string, data?: TprPrimarySalesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `tprPrimarySales/${saleId}`, document: doc };
}

/**
 * Authenticated buyer purchases MNY from the dev tranche. Buyer must equal @user.address. Price: if tprSalePrice/main exists, solAmountLamports must equal tprAmountBaseUnits * tprSalePrice/main.priceLamportsPerWholeToken / 1_000_000; otherwise falls back to tprAmountBaseUnits * TPR_PRIMARY_SALE_PRICE_LAMPORTS / 1_000_000. Two caps enforced atomically: (1) global tranche cap against tprPrimarySaleStats/main.totalSoldBaseUnits <= TPR_PRIMARY_SALE_CAP_BASE_UNITS, and (2) per-wallet cap against tprBuyerStats/<buyerAddress>.totalPurchasedBaseUnits <= TPR_PER_WALLET_CAP_BASE_UNITS (5,000 MNY = 5_000_000_000 base units). Hook: (1) transfers SOL from buyer to ADMIN, (2) transfers MNY from treasury PDA to buyer, (3) idempotently initializes or increments tprPrimarySaleStats/main.totalSoldBaseUnits, (4) idempotently initializes or increments tprBuyerStats/<@user.address>.totalPurchasedBaseUnits. isPassthrough=true so no permanent onchain row is stored. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setTprPrimarySales(saleId: string, data?: TprPrimarySalesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`tprPrimarySales/${saleId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting TprPrimarySales: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read primary-sale receipts (publicly verifiable).
   (Get Single Item)
 */
export async function getTprPrimarySales(saleId: string): Promise<TprPrimarySalesResponse | null> {
  try {
    const result = await get(`tprPrimarySales/${saleId}`);
    return result as TprPrimarySalesResponse | null;
  } catch (error) {
    console.error(`Error getting TprPrimarySales: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single TprPrimarySales document. (
  Read Operation Details: Anyone can read primary-sale receipts (publicly verifiable).
  )
 */
export function subscribeTprPrimarySales(callback: (data: TprPrimarySalesResponse | null) => void, saleId: string): Promise<() => Promise<void>> {
  return subscribe(`tprPrimarySales/${saleId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TprPrimarySalesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to TprPrimarySales at path '${`tprPrimarySales/${saleId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many TprPrimarySales items from collection tprPrimarySales
 
  Read Operation Details: Anyone can read primary-sale receipts (publicly verifiable).
  
 */
export async function getManyTprPrimarySales(filter: string = ""): Promise<TprPrimarySalesResponse[]> {
  try {
    const results = await get("tprPrimarySales", { prompt: filter });
    return Array.isArray(results) ? results as TprPrimarySalesResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprPrimarySales collection at path 'tprPrimarySales': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprPrimarySales collection at tprPrimarySales
 
  Read Operation Details: Anyone can read primary-sale receipts (publicly verifiable).
  
 */
export function subscribeManyTprPrimarySales(callback: (data: TprPrimarySalesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprPrimarySales", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprPrimarySalesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprPrimarySales collection at path '${"tprPrimarySales"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all TprPrimarySales items from collection tprPrimarySales
 
  Read Operation Details: Anyone can read primary-sale receipts (publicly verifiable).
  
 */
export async function getAllTprPrimarySales(filter: string = ""): Promise<TprPrimarySalesResponse[]> {
  try {
    const results = await get("tprPrimarySales", { prompt: filter });
    return Array.isArray(results) ? results as TprPrimarySalesResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprPrimarySales collection at path 'tprPrimarySales': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprPrimarySales collection at tprPrimarySales
 
  Read Operation Details: Anyone can read primary-sale receipts (publicly verifiable).
  
 */
export function subscribeAllTprPrimarySales(callback: (data: TprPrimarySalesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprPrimarySales", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprPrimarySalesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprPrimarySales collection at path '${"tprPrimarySales"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count TprPrimarySales items in collection tprPrimarySales.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countTprPrimarySales(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("tprPrimarySales", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting TprPrimarySales at path 'tprPrimarySales': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on TprPrimarySales items in collection tprPrimarySales.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateTprPrimarySales(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("tprPrimarySales", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating TprPrimarySales at path 'tprPrimarySales': ${formatError(error)}`);
    return { value: 0 };
  }
}

