// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: tprPrimarySaleStats/$id
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Singleton tracker for the TPR primary sale tranche. Holds cumulative totalSoldBaseUnits so the cap of 100,000 TPR (= 100,000 * 10^6 base units) can be enforced atomically. Created lazily by the first primary-sale purchase via @DocumentPlugin.updateField. The single document ID is 'main' (enforced via path constant in queries/UI).
 */

export interface TprPrimarySaleStatsRequest {
  totalSoldBaseUnits: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TprPrimarySaleStatsResponse {
  totalSoldBaseUnits: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * 
  Read Operation Details: Anyone can read the running total to compute remaining supply in the primary tranche.
   (Get Single Item)
 */
export async function getTprPrimarySaleStats(id: string): Promise<TprPrimarySaleStatsResponse | null> {
  try {
    const result = await get(`tprPrimarySaleStats/${id}`);
    return result as TprPrimarySaleStatsResponse | null;
  } catch (error) {
    console.error(`Error getting TprPrimarySaleStats: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single TprPrimarySaleStats document. (
  Read Operation Details: Anyone can read the running total to compute remaining supply in the primary tranche.
  )
 */
export function subscribeTprPrimarySaleStats(callback: (data: TprPrimarySaleStatsResponse | null) => void, id: string): Promise<() => Promise<void>> {
  return subscribe(`tprPrimarySaleStats/${id}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TprPrimarySaleStatsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to TprPrimarySaleStats at path '${`tprPrimarySaleStats/${id}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many TprPrimarySaleStats items from collection tprPrimarySaleStats
 
  Read Operation Details: Anyone can read the running total to compute remaining supply in the primary tranche.
  
 */
export async function getManyTprPrimarySaleStats(filter: string = ""): Promise<TprPrimarySaleStatsResponse[]> {
  try {
    const results = await get("tprPrimarySaleStats", { prompt: filter });
    return Array.isArray(results) ? results as TprPrimarySaleStatsResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprPrimarySaleStats collection at path 'tprPrimarySaleStats': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprPrimarySaleStats collection at tprPrimarySaleStats
 
  Read Operation Details: Anyone can read the running total to compute remaining supply in the primary tranche.
  
 */
export function subscribeManyTprPrimarySaleStats(callback: (data: TprPrimarySaleStatsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprPrimarySaleStats", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprPrimarySaleStatsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprPrimarySaleStats collection at path '${"tprPrimarySaleStats"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all TprPrimarySaleStats items from collection tprPrimarySaleStats
 
  Read Operation Details: Anyone can read the running total to compute remaining supply in the primary tranche.
  
 */
export async function getAllTprPrimarySaleStats(filter: string = ""): Promise<TprPrimarySaleStatsResponse[]> {
  try {
    const results = await get("tprPrimarySaleStats", { prompt: filter });
    return Array.isArray(results) ? results as TprPrimarySaleStatsResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprPrimarySaleStats collection at path 'tprPrimarySaleStats': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprPrimarySaleStats collection at tprPrimarySaleStats
 
  Read Operation Details: Anyone can read the running total to compute remaining supply in the primary tranche.
  
 */
export function subscribeAllTprPrimarySaleStats(callback: (data: TprPrimarySaleStatsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprPrimarySaleStats", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprPrimarySaleStatsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprPrimarySaleStats collection at path '${"tprPrimarySaleStats"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count TprPrimarySaleStats items in collection tprPrimarySaleStats.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countTprPrimarySaleStats(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("tprPrimarySaleStats", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting TprPrimarySaleStats at path 'tprPrimarySaleStats': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on TprPrimarySaleStats items in collection tprPrimarySaleStats.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateTprPrimarySaleStats(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("tprPrimarySaleStats", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating TprPrimarySaleStats at path 'tprPrimarySaleStats': ${formatError(error)}`);
    return { value: 0 };
  }
}

