// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: tprPurchases/$purchaseId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Buy records against an active tprListings entry. Atomically transfers SOL from buyer to seller and MNY from listing PDA to buyer, and marks the listing inactive.
 */

export interface TprPurchasesRequest {
  buyer: AddressType;
  listingId: string;
  totalSolLamports: number | TimeOperation | IncrementOperation | TokenAmount;
  seller: AddressType;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
  tprAmountBaseUnits: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TprPurchasesResponse {
  buyer: string;
  listingId: string;
  totalSolLamports: number;
  seller: string;
  ts: number;
  tprAmountBaseUnits: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a TprPurchases operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildTprPurchases(purchaseId: string, data?: TprPurchasesRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `tprPurchases/${purchaseId}`, document: doc };
}

/**
 * Authenticated buyer purchases an entire active listing. Frontend must pass listingId as the FULL document ID of the listing being bought. Buyer must equal @user.address. Server validates listing exists, is active, and snapshot fields (seller, amount, totalSol) match the listing. Hook: (1) transfers SOL from buyer to seller, (2) transfers MNY from listing PDA to buyer, (3) marks tprListings/$listingId.active = false. Atomic - any failure rolls back. NOTE: full-listing buys only; partial fills not supported. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setTprPurchases(purchaseId: string, data?: TprPurchasesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`tprPurchases/${purchaseId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting TprPurchases: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read purchase records (publicly verifiable).
   (Get Single Item)
 */
export async function getTprPurchases(purchaseId: string): Promise<TprPurchasesResponse | null> {
  try {
    const result = await get(`tprPurchases/${purchaseId}`);
    return result as TprPurchasesResponse | null;
  } catch (error) {
    console.error(`Error getting TprPurchases: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single TprPurchases document. (
  Read Operation Details: Anyone can read purchase records (publicly verifiable).
  )
 */
export function subscribeTprPurchases(callback: (data: TprPurchasesResponse | null) => void, purchaseId: string): Promise<() => Promise<void>> {
  return subscribe(`tprPurchases/${purchaseId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TprPurchasesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to TprPurchases at path '${`tprPurchases/${purchaseId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many TprPurchases items from collection tprPurchases
 
  Read Operation Details: Anyone can read purchase records (publicly verifiable).
  
 */
export async function getManyTprPurchases(filter: string = ""): Promise<TprPurchasesResponse[]> {
  try {
    const results = await get("tprPurchases", { prompt: filter });
    return Array.isArray(results) ? results as TprPurchasesResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprPurchases collection at path 'tprPurchases': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprPurchases collection at tprPurchases
 
  Read Operation Details: Anyone can read purchase records (publicly verifiable).
  
 */
export function subscribeManyTprPurchases(callback: (data: TprPurchasesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprPurchases", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprPurchasesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprPurchases collection at path '${"tprPurchases"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all TprPurchases items from collection tprPurchases
 
  Read Operation Details: Anyone can read purchase records (publicly verifiable).
  
 */
export async function getAllTprPurchases(filter: string = ""): Promise<TprPurchasesResponse[]> {
  try {
    const results = await get("tprPurchases", { prompt: filter });
    return Array.isArray(results) ? results as TprPurchasesResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprPurchases collection at path 'tprPurchases': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprPurchases collection at tprPurchases
 
  Read Operation Details: Anyone can read purchase records (publicly verifiable).
  
 */
export function subscribeAllTprPurchases(callback: (data: TprPurchasesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprPurchases", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprPurchasesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprPurchases collection at path '${"tprPurchases"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count TprPurchases items in collection tprPurchases.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countTprPurchases(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("tprPurchases", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting TprPurchases at path 'tprPurchases': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on TprPurchases items in collection tprPurchases.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateTprPurchases(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("tprPurchases", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating TprPurchases at path 'tprPurchases': ${formatError(error)}`);
    return { value: 0 };
  }
}

