// Generated by TaroBase SDK Generator: 2026-05-29T22:11:56.398Z
// Collection: tprToken/$tokenId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * MNY token. Fixed supply 1,000,000 (with 6 decimals = 1e12 base units) minted on creation to a treasury PDA. Admin-only creation - one-time setup. Treasury PDA serves as the source for the primary sale and future distributions.
 */

export interface TprTokenRequest {
  creator: AddressType;
  name: string;
  symbol: string;
  uri?: string;
  supply: number | TimeOperation | IncrementOperation | TokenAmount;
  ts: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface TprTokenResponse {
  creator: string;
  name: string;
  symbol: string;
  uri?: string;
  supply: number;
  ts: number;
  id: string;
  tarobase_created_at: number;
  tarobase_transaction_hash?: string | undefined; // Represents the hash of the transaction that created this item. Can be used to create Solscan links (combine with the current network in the Tarobase app)
}

/**
 * Build a TprToken operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildTprToken(tokenId: string, data?: TprTokenRequest): DocumentOperation {
  const doc = data ? transformValues(data) : {};
  return { path: `tprToken/${tokenId}`, document: doc };
}

/**
 * Admin-only one-time creation. $tokenId must equal @constants.TPR_TOKEN_ID. Creator must equal @user.address (the admin). Supply must equal TPR_INITIAL_SUPPLY (1,000,000 * 10^6 base units). Hook creates SPL mint with 6 decimals, derives a treasury PDA via @AccountPlugin.createAccount(TPR_TREASURY_ID), and mints the entire supply to that PDA. Tokens are minted to a PDA (not directly to PROJECT_VAULT_ADDRESS) so the Poof program can sign for primary-sale and listing transfers; SOL proceeds from the primary sale flow to ADMIN_ADDRESS as intended. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setTprToken(tokenId: string, data?: TprTokenRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data || {});
    const succeeded = await set(`tprToken/${tokenId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting TprToken: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Anyone can read token metadata.
   (Get Single Item)
 */
export async function getTprToken(tokenId: string): Promise<TprTokenResponse | null> {
  try {
    const result = await get(`tprToken/${tokenId}`);
    return result as TprTokenResponse | null;
  } catch (error) {
    console.error(`Error getting TprToken: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single TprToken document. (
  Read Operation Details: Anyone can read token metadata.
  )
 */
export function subscribeTprToken(callback: (data: TprTokenResponse | null) => void, tokenId: string): Promise<() => Promise<void>> {
  return subscribe(`tprToken/${tokenId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as TprTokenResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to TprToken at path '${`tprToken/${tokenId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many TprToken items from collection tprToken
 
  Read Operation Details: Anyone can read token metadata.
  
 */
export async function getManyTprToken(filter: string = ""): Promise<TprTokenResponse[]> {
  try {
    const results = await get("tprToken", { prompt: filter });
    return Array.isArray(results) ? results as TprTokenResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprToken collection at path 'tprToken': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprToken collection at tprToken
 
  Read Operation Details: Anyone can read token metadata.
  
 */
export function subscribeManyTprToken(callback: (data: TprTokenResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprToken", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprTokenResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprToken collection at path '${"tprToken"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all TprToken items from collection tprToken
 
  Read Operation Details: Anyone can read token metadata.
  
 */
export async function getAllTprToken(filter: string = ""): Promise<TprTokenResponse[]> {
  try {
    const results = await get("tprToken", { prompt: filter });
    return Array.isArray(results) ? results as TprTokenResponse[] : [];
  } catch (error) {
    console.error(`Error getting TprToken collection at path 'tprToken': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in TprToken collection at tprToken
 
  Read Operation Details: Anyone can read token metadata.
  
 */
export function subscribeAllTprToken(callback: (data: TprTokenResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("tprToken", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as TprTokenResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to TprToken collection at path '${"tprToken"}': ${formatError(error)}`);
    }
  });
}

/**
 * Count TprToken items in collection tprToken.
 * Returns a numeric count instead of fetching full documents — much more efficient.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param filter - Optional natural language filter (e.g., "created in the last 7 days")
 * @returns AggregateResult with the count value
 */
export async function countTprToken(filter: string = ""): Promise<AggregateResult> {
  try {
    return await count("tprToken", { prompt: filter || undefined });
  } catch (error) {
    console.error(`Error counting TprToken at path 'tprToken': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Run an aggregate operation on TprToken items in collection tprToken.
 * Returns a single numeric value instead of fetching full documents.
 *
 * Supported operations: 'count', 'uniqueCount', 'sum', 'avg', 'min', 'max'.
 * For 'sum', 'avg', 'min', 'max', and 'uniqueCount', you must provide the field name.
 *
 * NOTE: This only works because the read policy for this collection is "true".
 * @param operation - The aggregate operation to perform
 * @param opts - Options including optional filter prompt and field name
 * @returns AggregateResult with the computed numeric value
 */
export async function aggregateTprToken(operation: AggregateOperation, opts?: { filter?: string; field?: string }): Promise<AggregateResult> {
  try {
    return await aggregate("tprToken", operation, { prompt: opts?.filter || undefined, field: opts?.field });
  } catch (error) {
    console.error(`Error aggregating TprToken at path 'tprToken': ${formatError(error)}`);
    return { value: 0 };
  }
}

/**
 * Runs the "getTokenMintAddress" query on TprToken.
 * Query Logic: @TokenPlugin.getTokenMintAddress($tokenId, @data.name, @data.symbol)
 */
export async function runGetTokenMintAddressQueryForTprToken(tokenId: string, ): Promise<string> {
  try {
    const result = await runQuery(`tprToken/${tokenId}`, "getTokenMintAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getTokenMintAddress" on TprToken: ${formatError(error)}`);
    throw error;
  }
}

/**
 * Runs the "getTreasuryAddress" query on TprToken.
 * Query Logic: @AccountPlugin.getAccountAddress(@constants.TPR_TREASURY_ID)
 */
export async function runGetTreasuryAddressQueryForTprToken(tokenId: string, ): Promise<string> {
  try {
    const result = await runQuery(`tprToken/${tokenId}`, "getTreasuryAddress", {});
    return result as string;
  } catch (error) {
    console.error(`Error running query "getTreasuryAddress" on TprToken: ${formatError(error)}`);
    throw error;
  }
}

